- source/MoonScrollStrategy.js
2.5-upkeep version of PR #1869
> Fixes ENYO-592 on 2.5-upkeep

- css/Slider.less
- css/moonstone-dark.css
- css/moonstone-light.css
...when on a different sized screen.
> ENYO-724: Adjusted the positioning-fix on Slider to not scale

- css/moonstone-dark.css
- css/moonstone-light.css
- css/moonstone-rules.less
- source/moon-resolution.js
Reverting the changes from https://github.com/enyojs/moonstone/pull/1885, creating a PR for tracking purposes.
Revert "Merge pull request #1885 from enyojs/ENYO-720-revert-kunmyonchoi"
This reverts commit 65ee66624f34571211f166a5a22d5c8c59e3d8aa, reversing
changes made to d207356cda8327aee9854ea15dffb20620f174b7.
Conflicts:
css/moonstone-dark.css
css/moonstone-light.css
> ENYO-720: Update base font-size

- css/moonstone-dark.css
- css/moonstone-light.css
In https://github.com/enyojs/enyo/pull/991, we made a change to prevent certain measurements below a specific threshold from being scaled. The results of this change need to be reflected in the generated output.
We regenerate the CSS using the aforementioned change.
The Travis build is currently failing and should be re-run after https://github.com/enyojs/enyo/pull/991 is merged.
> ENYO-738: Generate CSS with minimum measurement values.

- source/Marquee.js
Cherry-picking the changes from https://github.com/enyojs/moonstone/pull/1880 into `2.5-gordon`, creating a PR for tracking purposes.
> ENYO-723 (2.5-gordon)

- source/Panels.js
moon.Panel.transitionFinished is not called by moon.Panels
Ensure that events and moon.Panel method calls occur at the same time
in the lifecycle regardless of moon.Panels animate state.
Depends upon enyojs/layout#110
Issue: ENYO-719
> Fixes ENYO-719

- source/Header.js
- source/Panel.js
Cherry-picking PR #1911 into master
> Fixes ENYO-799

- source/Panels.js
Cherry-picking the changes from https://github.com/enyojs/moonstone/pull/1915 into `master`, creating a PR for tracking purposes.
> ENYO-819 (master)

- css/Marquee.less
- css/moonstone-dark.css
- css/moonstone-light.css
This reverts commit 2d8948dc6faa16dfd4059e24925fa807e96a6c0d, reversing
changes made to d431e616ca704aefc821dc86ca675c37f21ee35a.
> Revert "Merge pull request #1927 from enyojs/ENYO-805-aarontam"

- samples/HistorySample.html
- samples/HistorySample.js
- source/VideoPlayer.js
- source/keymap.js
Requirement is
Close Info when it is open.
ENYO-518-davidum has common lib for back key support.
All of sub task branches are generated from it.
> Enyo 774 Implement back key support for VideoPlayer

- samples/HistorySample.html
- samples/HistorySample.js
- source/Popup.js
- source/keymap.js
Requirement is
Close (MODAL) popup
ENYO-518-davidum has common lib for back key support.
All of sub task branches are generated from it.
> ENYO-820 Implement back key support for Popup

- samples/HistorySample.html
- samples/HistorySample.js
- source/ContextualPopup.js
- source/keymap.js
Requirement is
Close opened ContextualPopup
ENYO-518-davidum has common lib for back key support.
All of sub task branches are generated from it.
> Enyo 858  Implement back key feature for ContextualPopup

- light-package.js
Cherry-picking the changes from https://github.com/enyojs/moonstone/pull/1950 into `master`, creating a PR for tracking purposes.
> ENYO-904 (master)

- .travis.yml
- css/Icon.less
- css/ItemOverlay.less
- css/moonstone-dark.css
- css/moonstone-light.css
- css/moonstone-rules.less
- css/moonstone-variables.less
- samples/ItemOverlaySample.css
- samples/ItemOverlaySample.html
- samples/ItemOverlaySample.js
- samples/package.js
- source/ItemOverlay.js
- source/Marquee.js
- source/package.js
Adding a new kind "moon.ItemOverlay" and "moon.ItemOverlaySupport" mixin with sample.
> ENYO-792: Support moon.Item Icon Overlay

- source/Panel.js
Cherry-picking the changes from https://github.com/enyojs/moonstone/pull/1946, creating a PR for tracking purposes.
> ENYO-886 (master)

- css/Dialog.less
- css/moonstone-dark.css
- css/moonstone-light.css
- source/Dialog.js
Cherry-picking changes from 2.5-upkeep branch.
> ENYO-905: Adding min-height on Dialog Title Area (master)

- .travis.yml
Effectively cherry-picking the Travis config changes from https://github.com/enyojs/moonstone/pull/1954 into `2.5-upkeep`, creating a PR for tracking purposes.
> Use the proper flags when invoking LESS.

- css/moonstone-dark.css
- css/moonstone-light.css
- css/moonstone-variables.less
2.5-upkeep version of #1947
**Note:** Commit 47ec6ad2f3ea862e51eaee4d6ab10a8958b9689a was omitted from this PR because the issue that added that code (ENYO-643) hasn't been merged into 2.5-upkeep.
> Fixes ENYO-891: Update grid row height.

- samples/All.js
- samples/CalendarSample.js
- samples/DatePickerSample.js
- samples/TimePickerSample.js
Cherry picking #1800 and #1819 into 2.5-upkeep
> Fixes ENYO-554

- source/Panels.js
Cherry-picking the changes from https://github.com/enyojs/moonstone/pull/1965 into `master`, creating a PR for tracking purposes.
> ENYO-874 (master)

- source/Panels.js
Cherry-picking the changes from https://github.com/enyojs/moonstone/pull/1965 into `release-2.5.3-pre.9.t`, creating a PR for tracking purposes.
> ENYO-874 (2.5.3-pre.9.t)

- css/moonstone-dark.css
- css/moonstone-light.css
- css/moonstone-rules.less
- source/moon-resolution.js
ENYO-958: Added aspect ratio detection and classes.
Caching and minor speed improvement in screen lookup functions.
> ENYO-958: Added aspect ratio detection and classes.

- source/Panels.js
Cherry-picking commits from https://github.com/enyojs/moonstone/pull/1969 into master branch.
> ENYO-890: Prevent running animation when no arrangement is needed.

- css/Dialog.less
- css/moonstone-dark.css
- css/moonstone-light.css
Cherry-picking changes from https://github.com/enyojs/moonstone/pull/1981 into 2.5-upkeep branch.
> ENYO-976: Adjust client position of Dialog.

- source/VideoPlayer.js
- source/VideoTransportSlider.js
Cherry-picking the changes from https://github.com/enyojs/moonstone/pull/1936 into `master`, creating a PR for tracking purposes.
> ENYO-875 (master)

- css/SelectionOverlaySupport.less
- css/moonstone-dark.css
- css/moonstone-light.css
- source/SelectionOverlaySupport.js
Modified SelectionOverlaySupport to have indicator in selection mode.
Show a ghost circle overlay only when selection mode is turned on. When the item is selected show check icon or user specified image within the circle having a spotted circle around it.
Updated css files.
[Updated based on https://github.com/enyojs/moonstone/pull/1964]
Enyo-DCO-1.1-Signed-off-by: Anish Ramesan <anish.ramesan@lge.com>
> ENYO-576: Selection mode indicator for GridList

- samples/ScrollerTextSample.js
- source/MoonScrollStrategy.js
- source/Scroller.js
Cherry-picking the changes from https://github.com/enyojs/moonstone/pull/1992/files into `master, creating a PR for tracking purposes.
> ENYO-1014 (master)

- css/moonstone-dark.css
- css/moonstone-light.css
- css/moonstone-variables.less
Cherry picking #1993 into 2.5-upkeep
> ENYO-1011: Adjust font-size for moon-body.

- css/CheckboxItem.less
- css/moonstone-dark.css
- css/moonstone-light.css
Cherry Picking #1989 into 2.5-upkeep
> ENYO-907: Remove unnecessary padding.

- source/Marquee.js
Marquee (when set marqueeOnHover as true) is not stop when focus moves to other control by 5way
Rather than hooking enyo.dispatcher, this creates a private component
that listens for the relevant events via enyo.Signals and stops the
active marquee control. Also extending it to stop marquee when
switching from pointer mode to 5-way as that's a synthetic onleave
for the purposes of Marquee.
> Fixes ENYO-1091

- source/DataGridList.js
Cherry-picking changes from 2.5-upkeep branch
> ENYO-1026: Call scroller stop on moon.DataGridList refresh

- source/LightPanel.js
> ENYO-944: Facade uppercase property of header, general refactoring.

- source/LightPanel.js
> ENYO-944: Small tweak to use string concatenation instead.

- source/Slider.js
Cherry-picking the changes from https://github.com/enyojs/moonstone/pull/2015/files into `release-2.5.3-pre.19.t`, creating a PR for tracking purposes.
> ENYO-1139 (release-2.5.3-pre.19.t)

- source/Slider.js
Cherry-picking the changes from https://github.com/enyojs/moonstone/pull/2015/files into `2.5-upkeep`, creating a PR for tracking purposes.
> ENYO-1139 (2.5-upkeep)

- source/VideoTransportSlider.js
> ENYO-23301: Start preview if necessary, when moving pointer in the slider.

- source/VideoTransportSlider.js
Cherry-picking the changes from https://github.com/enyojs/moonstone/pull/2014 into `2.5-upkeep`, creating a PR for tracking purposes.
> BHV-23301 (2.5-upkeep)

- source/VideoTransportSlider.js
Cherry-picking the changes from https://github.com/enyojs/moonstone/pull/2014 into `release-2.5.3-pre.19.t`, creating a PR for tracking purposes.
> BHV-23301 (release-2.5.3-pre.19.t)

- source/package.js
- source/wip-package.js
> ENYO-944: Moving LightPanels to WIP.

- source/ExpandablePicker.js
> ENYO-944: Clean-up.

- samples/PopupSample.html
- source/Popup.js
Ran into this while merging another PR and wanted to clean it up while it was still fresh. Due to some refactoring and clean-up in https://github.com/enyojs/moonstone/pull/1693, there were a few additional properties, methods, and calls, that were orphaned.
The unnecessary properties, methods, and calls have now been removed as necessary.
> ENYO-1159: Clean-up cruft.

- source/DataList.js
> Fixes ENYO-1289: Stop datalist scroller on collection changed

- css/Thumb-color.less
- css/moonstone-dark.css
- css/moonstone-dark.less
- css/moonstone-light.css
- css/moonstone-light.less
- Adding missing color scheme for scroll thumb
> ENYO-458: Adding Scroll Thumb color scheme for runtime change

- css/Calendar.less
- css/ChannelInfo.less
- css/Dialog.less
- css/Header.less
- css/Item.less
- css/ListActions.less
- css/VideoInfoHeader.less
- css/moonstone-dark.css
- css/moonstone-light.css
- css/moonstone-rules.less
- css/moonstone-text.less
- css/moonstone-variables-dark.less
- css/moonstone-variables-light.less
- css/moonstone-variables.less
- source/Header.js
* Header Title: #ccc
* Button text & icon (normal/selected): #ccc
* Divider line: #595959
* Unify button background color (except to deactivated): #4d4d4d
* Unify text color (normal): #a6a6a6
* Standardized spacing, updated to shorter CSS color format and, related variables that should be related.
> ENYO-1145: Updated colors to match latest design spec.

- source/LightPanel.js
This PR is dependent on https://github.com/enyojs/enyo/pull/1099.
> ENYO-944: Add hooks for panel activated/deactivated.

- source/NewDataList.js
- source/Scrollable.js
> ENYO-1341: Fixes for NewDataList and Scrollable

- css/VideoControlFullscreen.less
- css/moonstone-dark.css
- css/moonstone-light.css
Cherry-picking the changes from https://github.com/enyojs/moonstone/pull/2073 into `2.6.0-pre.4-dev`, creating a PR for tracking purposes.
> ENYO-1438 (2.6.0-pre.4-dev)

- source/Scrollable.js
> ENYO-1444: moon.Scrollable: spot nearest chid

- lib/Calendar/Calendar.js
- lib/Clock/Clock.js
- lib/DatePicker/DatePicker.js
- lib/DateTimePickerBase/DateTimePickerBase.js
- lib/Slider/Slider.js
- lib/TimePicker/TimePicker.js
- lib/VideoFeedback/VideoFeedback.js
- lib/VideoPlayer/VideoPlayer.js
- lib/VideoTransportSlider/VideoTransportSlider.js
- lib/fonts.js
- lib/i18n.js
ilib is now treated as mandatory for moonstone so all conditionals that
check for the existence of ilib can be removed and only the ilib code
path should remain
> Remove conditionals for ilib

- source/NewDataList.js
- source/Scrollable.js
> Scrolling tweaks: Fix 5-way guard code, unspot when suppressing

- lib/VideoFeedback/VideoFeedback.js
Some leftover $lib references
remove $lib reference
> Fixes ENYO-1522

- source/Scrollable.js
> Scrollable: only unspot when in pointer mode

- lib/VideoPlayer/VideoControlFullscreen.less
Cherry-picking the changes from https://github.com/enyojs/moonstone/pull/2077 into `2.6.0-dev`, creating a PR for tracking purposes.
> ENYO-1438: make css of videoPlayer's iconButton like REW/FF be effective... (2.6.0-dev)

- lib/NewDataList/NewDataList.js
- lib/ScrollControls/ScrollControls.js
- lib/Scrollable/Scrollable.js
Migrated to modularized codebase for merging into 2.6.0-dev.
Depends on https://github.com/enyojs/spotlight/pull/174 for `spotlightRememberFocus`.
> Compilation of changes since 2.6.0-pre.4

- lib/Marquee/Marquee.js
Modify target element that will be accelerated from 'this' to 'this.$.marqueeText'.
> ENYO-1194 Set HW accelerate to actual animation element in moon.MarqueeText

- lib/DataGridList/DataGridList.js
Correct delegate reference for DataGridList
> Fixes ENYO-1587

- lib/NewDataList/NewDataList.js
Also, fix a missing-variable-declaration issue found when running JSHint.
> ENYO-1617: Factor Spotlight support out of enyo/VirtualDataRepeater

- lib/Slider/Slider.js
- lib/Slider/Slider.less
Issue
-------
There is UX requirement to add arrow indicator for slider
Implemented
-----------------
Using iconButton which is in simplePIcker, I add arrow buttons into both sides of slider.
> Enyo 1144 Slider: Insert arrow indicators on tool tip when selecting knob

- source/Slider.js
Cherry-picking the changes from https://github.com/enyojs/moonstone/pull/2116, creating a PR for tracking purposes.
> ENYO-1529 (2.5.4-pre.16)

- lib/DayPicker/DayPicker.js
Change from https://github.com/enyojs/moonstone/pull/2154.
> ENYO-1660: update to handle several countries case(fa-IR, ku-Arab-IQ, he-IL, and xx-IN)

- css/moonstone-mixins.less
- lib/VideoPlayer/VideoPlayer.less
> DRD-8143: Consolidate styles into mixins.

- lib/ScrollStrategy/ScrollStrategy.js
Changes from https://github.com/enyojs/moonstone/pull/2185.
> ENYO-1566: Scroller doesn't display last line when using p tag on content

- lib/Slider/Slider.js
- lib/Slider/Slider.less
Slider was reusing a class from SimplePicker
Refactor Slider CSS a bit to include the relevant positioning styles
> Fixes ENYO-1711

- css/moonstone-variables-dark.less
- css/moonstone-variables-light.less
- lib/Button/Button.js
- lib/Button/Button.less
- lib/IconButton/IconButton.js
- lib/IconButton/IconButton.less
- lib/NewPagingControl/NewPagingControl.js
- lib/PagingControl/PagingControl.js
- lib/SimplePicker/SimplePicker.js
- lib/Slider/Slider.js
I refactored what you had to match up with what I was thinking about.
This code does the following:
* Implements just translucent and transparent, opaque is the default so it doesn't have any special rules.
* Implements the background opacity of the pressed states of buttons, as well as allows spotlight to still look correct.
* Addresses the disabled state questions.
* Updates all existing controls to use the new technique.
> Slightly different approach to translucency

- css/Checkbox.less
- css/CheckboxItem.less
- css/ExpandableListItem.less
- css/ExpandablePicker.less
- css/Header.less
- css/Item.less
- css/RadioItem.less
- css/moonstone-dark.css
- css/moonstone-light.css
- css/moonstone-variables.less
> ENYO-1619: Adjusted text containers' heights to allow for taller international characters

- lib/Marquee/Marquee.js
> ENYO-1799: MarqueeItem contains wrong reference for util and platform

- source/Marquee.js
Adding a commit I forgot to push to the branch associated with the original PR https://github.com/enyojs/moonstone/pull/2219.
> ENYO-1285: Small formatting tweak.

- lib/DatePicker/DatePicker.js
> ENYO-1354 Prevent passing undefined values to ilib

- lib/History/History.js
> ENYO-1854 Fix HistorySupport

- lib/fonts.js
Update module reference for enyo/i18n
> Fixes ENYO-1840

- lib/AudioPlayback/package.json
- lib/DataTable/DataTable.js
> ENYO-1865: Lib build fix

- lib/Panel/Panel.js
Changes from https://github.com/enyojs/moonstone/pull/2208.
> ENYO-1773: Add onanimationend on viewport of moon.Panel

- lib/LightPanel/LightPanel.less
> ENYO-1874: Add padding-top for LightPanel client

- css/Accordion.less
- css/Checkbox.less
- css/CheckboxItem.less
- css/Dialog.less
- css/ExpandableListItem.less
- css/ExpandablePicker.less
- css/FormCheckbox.less
- css/Header.less
- css/ImageItem.less
- css/InputDecorator.less
- css/Item.less
- css/LabeledTextItem.less
- css/RadioItem.less
- css/SelectableItem.less
- css/moonstone-dark.css
- css/moonstone-light.css
- css/moonstone-variables.less
- samples/package.js
Reverting https://github.com/enyojs/moonstone/pull/2214 and https://github.com/enyojs/moonstone/pull/2216.
> ENYO-1619 (revert)

- lib/Button/Button.js
- lib/ListActions/ListActions.js
app devs need backgroundOpacity property for ListActions
made backgroundOpacity for ListActions
Enyo-DCO-1.1-Signed-off-by: Suhyung Lee suhyung2.lee@lge.com
> ENYO1849 : need API to set 'backgroundOpacity' property in ListAction

- css/moonstone-variables.less
- lib/Tooltip/Tooltip.js
- lib/Tooltip/Tooltip.less
Tooltip only supports a single line of text and multiline support is desired.
Rework CSS and positioning logic to support a `components` block of multiple children
> Fixes ENYO-1483

- lib/Dialog/Dialog.js
moonstone/Dialog needs to support either content or components in its body
Add enyo/ContentAreaSupport to moonstone/Dialog
> Fixes ENYO-1543

- css/moonstone-variables.less
- lib/Accordion/Accordion.less
- lib/Checkbox/Checkbox.less
- lib/CheckboxItem/CheckboxItem.less
- lib/Dialog/Dialog.less
- lib/Divider/Divider.less
- lib/ExpandableListItem/ExpandableListItem.less
- lib/ExpandablePicker/ExpandablePicker.less
- lib/FormCheckbox/FormCheckbox.less
- lib/Header/Header.less
- lib/ImageItem/ImageItem.less
- lib/Item/Item.less
- lib/ItemOverlay/ItemOverlay.less
- lib/LabeledTextItem/LabeledTextItem.less
- lib/RadioItem/RadioItem.less
- lib/SelectableItem/SelectableItem.less
Resubmitting the changes from #2209 
> Fixes ENYO-1830

- lib/TooltipDecorator/TooltipDecorator.js
- lib/TooltipDecorator/TooltipDecorator.less
- lib/TooltipDecorator/package.json
> ENYO-1792 Tooltip: Tooltip image position fault

- lib/ItemOverlay/ItemOverlay.js
Changes from https://github.com/enyojs/moonstone/pull/2244.
> ENYO-1856 (2.6.0-pre.11.1)

- source/VideoTransportSlider.js
> ENYO-2047: Give margin on duration text of progressBar

- lib/ExpandablePicker/ExpandablePicker.js
Changes from https://github.com/enyojs/moonstone/pull/2308.
> ENYO-2075: Switch order of setting active state and header spotting.

- lib/i18n.js
- package.json
> ENYO-2114: Fix localization asset pathing

- lib/DatePicker/DatePicker.js
- lib/DateTimePickerBase/DateTimePickerBase.js
- lib/TimePicker/TimePicker.js
Changes from https://github.com/enyojs/moonstone/pull/2299.
> ENYO-2091 (2.6.0-dev)

- lib/ExpandableInput/ExpandableInput.js
> ENYO-2081: Provide ExpandableInput access to set input's attribute

- lib/InputHeader.js
> ENYO-2156 Marked InputHeader deprecated

- lib/LabeledTextItem/LabeledTextItem.js
> Fixes ENYO-1798

- lib/Scroller/Scroller.js
After the scrolling completes following by PageUp/Down key, the top item in the scroll frame does not get re-spotted.
Update PageUp/Down key handing based on description of new behavior (in ENYO-1330)
Enyo-DCO-1.1-Signed-off-by: Sungbae Cho sb.cho@lge.com
> ENYO-1330: Update PageUp/Down key handling based on new ux

- lib/ProgressBar/ProgressBar.js
- lib/ProgressBar/ProgressBar.less
- lib/Slider/Slider.js
- lib/Slider/Slider.less
Also changed the way that incremental slider is structured to be simpler and follow inheritable rules.
> ENYO-1958: Implemented vertical slider

- lib/ProgressBar/ProgressBar.js
- lib/ProgressBar/ProgressBar.less
- lib/Slider/Slider.js
- lib/Slider/Slider.less
This reverts commit ff383ace9c4984102a08755027a76f70549e67c3, reversing
changes made to 4478e1a18d957b24994dc636e15dba692ea139d5.
> Revert "Merge pull request #2382 from enyojs/ENYO-1958-blakestephens"

- css/moonstone-mixins.less
> allow standalone builds of moonstone to continue for now

- samples/TimePickerSample.js
- source/DatePicker.js
- source/DateTimePickerBase.js
- source/TimePicker.js
Issue
-------
Make timePicker support Ethiopia time
Fix
----
Current timePicker does not consider that meridiem has some entries more than two -AM & PM-
Fix related logic
> Wp 774 TimePicker support Ethiopia 

- css/moonstone-variables.less
Spinner looks much less lazy now.
_This PR should be profoundly easy to review. Good luck_
> ENYO-2305: Pepped up the spinner a bit

- css/moonstone-rules.less
- lib/ScrollThumb/ScrollThumb.less
> ENYO-2330: Scroll thumb displaced vertically

- lib/ContextualPopupButton/ContextualPopupButton.less
> ENYO-2332: ContextualPopupButton collapsed by content

- lib/Popup/Popup.less
> ENYO-2334: Popup close button misaligned and with background color

- lib/RadioItem/RadioItem.less
> ENYO-2329 RadioItem fails to pad for text

- lib/ContextualPopup/ContextualPopup.js
Correct reference to enyo/History
> Fixes ENYO-2357

- lib/ExpandablePicker/ExpandablePicker.js
* Allow deselecting a control by setting selectedIndex to -1
* Correctly update currentValueText when destroyClientControls called
> Fixes ENYO-2362

- css/moonstone-variables-dark.less
- css/moonstone-variables-light.less
- lib/ContextualPopup/ContextualPopup.js
- lib/Dialog/Dialog.js
- lib/ListActions/ListActions.js
- lib/Popup/Popup.less
This adds a level of precedence that resolves the previous precedence/ordering issue.
_Cruft is also removed._
> ENYO-2334: Applied backgroundOpacity rules to closeButton (moon-popup-close)

- src/ContextualPopupButton/ContextualPopupButton.less
> ENYO-2401 ContextualPopup: Disabled Text is Hidden

- src/NewPagingControl/NewPagingControl.js
> ENYO-2109: NewPagingControl: End hold on bounce

- src/DatePicker/DatePicker.js
- src/DatePicker/DatePicker.less
- src/DateTimePickerBase/DateTimePickerBase.js
- src/DateTimePickerBase/DateTimePickerBase.less
- src/DateTimePickerBase/package.json
- src/TimePicker/TimePicker.js
- src/TimePicker/TimePicker.less
> ENYO-2433 Missing dependency from Date/TimePicker

- src/Marquee/Marquee.js
Enyo-DCO-1.1-Signed-off-by: Igor Kuzko <igor.kuzko@lge.com>
> ENYO-2208: ToggleItem: Marquee Does not Restart

- src/LightPanels/LightPanel.js
- src/LightPanels/LightPanels.js
- src/Panels/Panels.js
Adds accessibility support to LighPanel
> Fixes ENYO-1994

- src/IntegerPicker/IntegerPicker.js
> ENYO-2411 IntegerPicker does not update range at creation

- src/Marquee/Marquee.js
Enyo-DCO-1.1-Signed-off-by: Igor Kuzko <igor.kuzko@lge.com>
> ENYO-2436: Marquee will not continue after spot when marqueeOnRender

- src/Spinner/Spinner.js
Spinner is not spotlight component, so added alert role to read
spinner content. Also set accessibilityLive to 'off' to prevent
read marqueeText continuosly.
https://jira2.lgsvl.com/browse/PLAT-6920
> PLAT-6920: Add Text to Speech Accessibility support to Spinner

- src/GridListImageItem/GridListImageItem.js
> Make image placeholder public

- src/ProgressBar/ProgressBar.js
fix aria-valuetext determination for ProgressBar
> Fixes ENYO-1984

- src/Slider/Slider.js
For original work see https://github.com/enyojs/moonstone/pull/2410.
Enyo-DCO-1.1-Signed-Off-By: Cole Davis (cole.davis@lge.com)
Reviewed-By: Aaron Tam (aaron.tam@lge.com)
Integrated-By: Cole Davis (cole.davis@lge.com)
> squash many commits for work down by David Um (@DavidUM)

- src/Dialog/Dialog.js
- src/Slider/Slider.js
Chaged slider accessibility code to meet ux.
- When the slider focused, it reads value(including popup content
or value percentage).
- When the slider selected, it reads the hint
'change a value with left right button'
- When the value is changed, it reads current value.
- If there are left/right(up/down) button and when they are focused
it reads 'value' + 'press ok button to decrease/increase the value'
- When the value is changed with left/right button, it reads
current value
Additional
- set 'close' as accessibilityLabel on close button in dialog
https://jira2.lgsvl.com/browse/ENYO-2295
nyo-DCO-1.1-Signed-off-by: Jaewon Jang <jaewon98.jang@lgepartner.com>
> ENYO-2295: Accessibility scenario of the slider is changed

- src/ListActions/ListActions.js
Signed-off-by: David Joonho Um <david.um@lge.com>
> Enyo-2523 Drop history entry when ListAction closed with 'x' button

- src/ScrollStrategy/ScrollStrategy.js
> Fixes ENYO-2439 setup scroll bounds before determining scrollability

- src/ContextualPopup/ContextualPopup.js
- src/Popup/Popup.js
We had a miss communication between HE UX.
So, I'd like to revert feature and will have discussion with @mediachild and UBeon, Heo(ubeom.heo@lge.com)
> Enyo 2517 Revert PLAT-7063

- src/Drawers/Drawers.js
fix changing drawer activator icon at runtime
> Fixes ENYO-2496

- src/InputDecorator/InputDecorator.js
batch accessibility changes in InputDecorator
> Fixes ENYO-2519

- src/IconButton/IconButton.js
- src/PagingControl/PagingControl.js
Adds accessibility support for paging controls
> Fixes PLAT-6939

- src/Header/Header.less
> Non-latin -> RTL class name mistake correction.

- src/ListActions/ListActions.js
> ENYO-2631: Updated ListActions to use the newer customization API.

- src/fonts.js
> DRD4TV-3571: Added custom font support for en-JP locale (English in Japan)

- css/moonstone-variables.less
- src/Spinner/Spinner.less
Also restored the inertial ball-bounce.
> ENYO-2670: Detoxed the Spinner from its speed addiction 🏥

- src/IntegerPicker/IntegerPicker.js
> ENYO-2676 IntegerPicker 'range' does not update when 'step' is changed

- src/NewPagingControl/NewPagingControl.js
Requirement
1) Screen reader should read scroll IconButton string when IconButton is focused.
2) Screen reader should read scroll direction string whenever this scroll iconButton is pressed.
Implementation
For NewPagingControl Accessibility
Add onSpotlightKeyUp handler.
Add private property spotted and pressed.
When spotted is true, set accessibilityLabel 'scroll up'.
When pressed is true, set accessibilityAlert and accessibilityLabel to read
changed label automatically.
https://jira2.lgsvl.com/browse/PLAT-8615
> PLAT-8615: Add Text to Speech Accessibility support to NewPagingControl

- src/Dialog/Dialog.js
- src/Drawers/Drawers.js
- src/ExpandableInput/ExpandableInput.js
- src/InputDecorator/InputDecorator.js
- src/IntegerPicker/IntegerPicker.js
- src/NewPagingControl/NewPagingControl.js
- src/PagingControl/PagingControl.js
- src/SimpleIntegerPicker/SimpleIntegerPicker.js
- src/Slider/Slider.js
As per TVL finalized translate due date. we've requested to modify
accessibility string with substitution string witch has been translated already.
If there is no substitution string, we should remove the strings.
I want to leave the logic for accessibility hint because we may be able to apply
them on MR
https://jira2.lgsvl.com/browse/PLAT-10203
> PLAT-10203: Modify Accessibility string for multi language support

- src/ProgressBar/ProgressBar.js
update popup when showPercentage changes
> Fixes ENYO-2285

- css/moonstone-variables-dark.less
> ENYO-2726: Corrected icon color of IconButton pressed state

- src/LightPanels/LightPanel.js
spot the placeholder only its the only spottable option
> Fixes ENYO-2757

- src/ListActions/ListActions.js
So it can execute necessary changes that may have happened at a higher level without its knowledge.
> ENYO-2701: ListActions is now aware of when its parent panel is onscreen

- src/ExpandableListItem/ExpandableListItem.js
use correct currently spotted control based on pointer mode
> Fixes ENYO-2736

- src/Spinner/Spinner.less
Changes from https://github.com/enyojs/moonstone/pull/2627.
> ENYO-2778 (2.6.0-pre.19.1)

- src/ExpandableInput/ExpandableInput.js
Changes from https://github.com/enyojs/moonstone/pull/2622.
> ENYO-2751 (2.6.0-pre.19.1)

- src/DataList/DataList.js
Changes from https://github.com/enyojs/moonstone/pull/2631.
> ENYO-2797 (cherry-pick for 2.6.0-pre.19.2)

- src/Panels/Panels.js
This reverts commit a8ccfcee0bd36d951494646ee567b513d411049b, reversing
changes made to 00936bc5ec56340d80c7c743be970e1205bee16a.
> Revert "Merge pull request #2609 from enyojs/ENYO-2485-jaewonjang"

- src/Panels/Panels.js
Changes from https://github.com/enyojs/moonstone/pull/2635.
This reverts commit a8ccfcee0bd36d951494646ee567b513d411049b, reversing
changes made to 00936bc5ec56340d80c7c743be970e1205bee16a.
> Revert "Merge pull request #2609 from enyojs/ENYO-2485-jaewonjang" (2.6.0-pre.19.2)

- src/DataList/DataList.js
We made some recent changes to fully support restoring scroll position and selected index when re-rendering a `DataList` (i.e. for a cached view). If the position and/or index to restore was part of a page whose index was not part of the initial, default generated pages (index 0 and 1), we could be generating 4 pages when rendering, as we would be generating the initial pages, and then the desired pages.
To limit the scope of this fix and minimize side-effects in the core `enyo/DataList` and `enyo/VerticalDelegate` kinds, we kept the fix in Moonstone and overrode the `reset` method, conditionally generating the desired pages if we had a position and/or index to show, otherwise we would execute the default behavior of generating the initial set of pages.
Slight bit of dyslexia - the branch …
> ENYO-2817: Prevent double page generation when restoring focused index.

- src/LabeledTextItem/LabeledTextItem.js
- src/LabeledTextItem/LabeledTextItem.less
...and style based on whether text is provided.
> ENYO-2825: Assigning text to a LabeledTextItem also sets its visibility

- src/ScrollStrategy/ScrollStrategy.js
> Fixes ENYO-2861 use first spottable parent when determining 5-way limit

- src/ProgressBar/ProgressBar.js
- src/Slider/Slider.js
Reverts #2648 and combines the aria value observers for Slider and
ProgressBar to simplify the logic.
> Fixes ENYO-2844

- src/LightPanels/LightPanel.js
- src/LightPanels/LightPanels.js
- src/NewDataList/NewDataList.js
- src/NewPagingControl/NewPagingControl.js
- src/ScrollControls/ScrollControls.js
- src/Scrollable/Scrollable.js
- src/StyleAnimator/StyleAnimator.js
> ENYO-2917 Document wip modules/kinds

- src/HistorySupport/HistorySupport.js
> ENYO-2964 Fix mixin declarations

- src/Drawers/Drawers.js
- src/ExpandableInput/ExpandableInput.js
- src/InputDecorator/InputDecorator.js
- src/IntegerPicker/IntegerPicker.js
- src/NewPagingControl/NewPagingControl.js
- src/PagingControl/PagingControl.js
- src/SimpleIntegerPicker/SimpleIntegerPicker.js
- src/Slider/Slider.js
We had modified temporarily accessibility string with substitution string
witch has been translated already.
Now we can request translation for 2016 TV MR and restore it to the original
string.
https://jira2.lgsvl.com/browse/PLAT-10884
Enyo-DCO-1.1-Signed-off-by: Jaewon Jang jaewon98.jang@lgepartner.com
> PLAT-10884: Remodify Accessibility string for multi language support

- src/DataGridList/DataGridList.js
> ENYO-2646 Move scaling out of constructor to create

- src/SimplePicker/SimplePicker.js
> Fixes ENYO-2962 add single space accessibilityLabel to suppress icon in aria-label

- src/ScrollStrategy/ScrollStrategy.js
> Fixes ENYO-2992 fix handling of zero wheelDeltaX in horizontally scrollable Scroller

- src/Drawers/Drawer.js
- src/ExpandableInput/ExpandableInput.js
- src/ExpandableIntegerPicker/ExpandableIntegerPicker.js
- src/HighlightText/HighlightText.js
- src/Image/Image.js
- src/ListActions/ListActions.js
- src/Panel/Panel.js
- src/Panels/Panels.js
- src/Popup/Popup.js
- src/RichText/RichText.js
- src/Scroller/Scroller.js
- src/SelectableItem/SelectableItem.js
- src/Spinner/Spinner.js
- src/StyleAnimator/StyleAnimator.js
- src/ToggleButton/ToggleButton.js
- src/VideoFeedback/VideoFeedback.js
- src/fonts.js
> ENYO-3018 Fixup doc deficiencies

- src/ScrollStrategy/ScrollStrategy.js
- src/Scroller/Scroller.js
> ENYO-3040: Scroller issue on Signage

- src/ScrollStrategy/ScrollStrategy.js
- src/Scroller/Scroller.js
Changes from https://github.com/enyojs/moonstone/pull/2690.
> ENYO-3040 (2.6.2-rc.2)

- src/ListActions/ListActions.js
> Fixes ENYO-3073 unmute tooltip before spotting activator

- src/IntegerPicker/IntegerPicker.js
> ENYO-3068: IntegerPicker: Changes in value look janky on touch devices

- src/ContextualPopupButton/ContextualPopupButton.js
- src/ContextualPopupDecorator/ContextualPopupDecorator.js
> PLAT-16231: Change defaultKind from ContextualPopupButton to Button

- css/moonstone-variables.less
- src/Dialog/Dialog.js
- src/Dialog/Dialog.less
- src/Popup/Popup.less
* Title, SubTitle, and Divider are all optional now. Buttons relocated to the bottom.
* Popup had a minor change to provide safe-padding around the X-Close button (things were running into it)
* Layout updated with the latest sizing/positioning specs from GUI.
> ENYO-2954: API and layout for Dialog established

- src/SimplePicker/SimplePicker.js
Changes from https://github.com/enyojs/moonstone/pull/2646.
> ENYO-2597 (2.6.3-rc.1)

- src/ContextualPopupDecorator/ContextualPopupDecorator.js
Changes from https://github.com/enyojs/moonstone/pull/2664.
> ENYO-2330 (2.6.3-rc.1)

- src/ProgressBar/ProgressBar.js
- src/Slider/Slider.js
Changes from https://github.com/enyojs/moonstone/pull/2660.
> ENYO-2844 (2.6.3-rc.1)

- src/Drawers/Drawers.js
- src/ExpandableInput/ExpandableInput.js
- src/InputDecorator/InputDecorator.js
- src/IntegerPicker/IntegerPicker.js
- src/NewPagingControl/NewPagingControl.js
- src/PagingControl/PagingControl.js
- src/SimpleIntegerPicker/SimpleIntegerPicker.js
- src/Slider/Slider.js
Changes from https://github.com/enyojs/moonstone/pull/2673.
> PLAT-10884 (2.6.3-rc.1)

- src/Panels/Panels.js
Changes from https://github.com/enyojs/moonstone/pull/2642.
> ENYO-2804 (2.6.3-rc.1)

- src/SimplePicker/SimplePicker.js
Changes from https://github.com/enyojs/moonstone/pull/2681.
> ENYO-2962 (2.6.3-rc.1)

- src/Popup/Popup.js
Changes from https://github.com/enyojs/moonstone/pull/2675.
> ENYO-2955 (2.6.3-rc.1)

- src/IntegerPicker/IntegerPicker.js
- src/SimpleIntegerPicker/SimpleIntegerPicker.js
Changes from https://github.com/enyojs/moonstone/pull/2697.
> PLAT-14806 (2.6.3-rc.1)

- src/LightPanels/LightPanel.js
Changes from https://github.com/enyojs/moonstone/pull/2692.
> ENYO-2784 (2.6.3 rc.1)

- src/ListActions/ListActions.js
Changes from https://github.com/enyojs/moonstone/pull/2699.
> ENYO-3073 (2.6.3-rc.1)

- src/CheckboxItem/CheckboxItem.less
Changes from https://github.com/enyojs/moonstone/pull/2696.
> ENYO-2907 (2.6.3-rc.1)

- src/NewDataList/NewDataList.js
- src/Scrollable/Scrollable.js
Changes from https://github.com/enyojs/moonstone/pull/2705.
> ENYO-3074 (2.6.3 rc.1)

- src/Slider/Slider.js
- src/Slider/Slider.less
Changes from https://github.com/enyojs/moonstone/pull/2728.
> PLAT-15388 (2.6.4-rc.1)

- src/DateTimePickerBase/DateTimePickerBase.js
- src/ExpandableInput/ExpandableInput.js
- src/ExpandableListItem/ExpandableListItem.js
- src/ExpandablePicker/ExpandablePicker.js
Changes from https://github.com/enyojs/moonstone/pull/2691.
> PLAT-15389 (2.6.4 rc.1)

- src/ContextualPopupButton/ContextualPopupButton.js
- src/ContextualPopupDecorator/ContextualPopupDecorator.js
- src/ToggleText/ToggleText.js
Changes from https://github.com/enyojs/moonstone/pull/2694.
> PLAT-16231 (2.6.4 rc.1)

- css/moonstone-variables.less
- src/Dialog/Dialog.js
- src/Dialog/Dialog.less
- src/Popup/Popup.less
Changes from https://github.com/enyojs/moonstone/pull/2702.
> ENYO-2954 (2.6.4-rc.1)

- src/Popup/Popup.js
Changes from https://github.com/enyojs/moonstone/pull/2727.
> ENYO-3091 (2.6.4-rc.1)

- src/FormCheckbox/FormCheckbox.less
> Form checkbox spotlight color was assigned incorrectly.

- css/moonstone-variables-dark.less
- css/moonstone-variables-light.less
- src/ContextualPopup/ContextualPopup.js
- src/Popup/Popup.less
Corrected an inappropriate color assignment in Popup's style.
> ENYO-3172: ContextualPopup now has the neutral theme in the right place

- css/moonstone-variables-dark.less
- css/moonstone-variables-light.less
- css/moonstone-variables.less
Changes from https://github.com/enyojs/moonstone/pull/2710.
> ENYO-3083 (2.6.4-rc.1)

- css/moonstone-variables-dark.less
- css/moonstone-variables-light.less
- src/ContextualPopup/ContextualPopup.js
- src/Popup/Popup.less
Changes from https://github.com/enyojs/moonstone/pull/2745.
> ENYO-3172 (2.6.4-rc.1)

- src/ExpandableDataPicker/ExpandableDataPicker.js
Changes from https://github.com/enyojs/moonstone/pull/2711.
> ENYO-3101 (2.6.4-rc.1)

- index.js
add require for enyo-ilib to ensure inclusion of locale assets
> Fixes ENYO-3165

- src/Checkbox/Checkbox.js
- src/ContextualPopup/ContextualPopup.js
- src/SelectableItem/SelectableItem.js
- src/fonts.js
Enyo-DCO-1.1-Signed-off-by: Jeremy Thomas <jeremy.thomas@lge.com>
> ENYO-3019: Remove IE8 support

- src/Item/Item.less
Changes from https://github.com/enyojs/moonstone/pull/2754.
> ENYO-3186 (2.6.4-rc.1)

- css/moonstone-mixins.less
- src/IconButton/IconButton.less
And mixin updated/added for alternate case.
> ENYO-3207: IconButton now has its own tap area rules

- css/moonstone-mixins.less
- src/IconButton/IconButton.less
Changes from https://github.com/enyojs/moonstone/pull/2755.
> ENYO-3207 (2.6.3-rc.2)

- src/ExpandableListItem/ExpandableListItem.less
- src/ImageItem/ImageItem.less
- src/LabeledTextItem/LabeledTextItem.less
> ENYO-3197: Fix spotlight color and display for header text

- css/moonstone-variables-dark.less
- css/moonstone-variables-light.less
- src/ContextualPopup/ContextualPopup.less
- src/ContextualPopupButton/ContextualPopupButton.less
> ENYO-3220: Fix ContextualPopup colors to neutral colors

- css/moonstone-variables-dark.less
- src/FormCheckbox/FormCheckbox.less
- src/IconButton/IconButton.less
- src/Popup/Popup.js
Changes from https://github.com/enyojs/moonstone/pull/2709 and https://github.com/enyojs/moonstone/pull/2744.
> PLAT-16900 (2.6.4-rc.1)

- css/moonstone-variables-dark.less
- css/moonstone-variables-light.less
- src/ContextualPopup/ContextualPopup.less
- src/ContextualPopupButton/ContextualPopupButton.less
Changes from https://github.com/enyojs/moonstone/pull/2765.
> ENYO-3220 (2.6.4-rc.1)

- src/ContextualPopup/ContextualPopup.js
- src/Popup/Popup.js
> PLAT-16199: Change default value of spotlightModal and showCloseButton

- src/Tooltip/Tooltip.js
- src/Tooltip/Tooltip.less
Tooltip nub also got a makeover in all cases, and now looks more like the original spec.
> ENYO-2709: Added support for sideways-facing tooltips

- src/ListActions/ListActions.less
> ENYO-3232: Fix arrow position calculation

- src/ContextualPopup/ContextualPopup.js
> ENYO-3233: Prevent event bubbling when close button is tapped

- src/Tooltip/Tooltip.js
At a general level, the tooltip tail overlaps the activator. We had increased the size of the tail due to some recent optimizations and support for sideways tooltips, but the default margin was set to a static size in the JS. Additionally, when using a non-floating tooltip, the tooltip is positioned relative to the activator, and does not take into account any potential border width of the activator.
To resolve the first overlapping issue, we have noted the `18px` tail size of the tooltip, and increased the default margin to `21px` to accommodate this. To take into account the border width of the activator, we add the width of the left border to the position for a `left *` positioned tooltip, as the positioning is relative to the element excluding the border. For a `right *` positioned …
> ENYO-3242: Better non-floating tooltip support.

- src/Tooltip/Tooltip.js
- src/Tooltip/Tooltip.less
Enyo-DCO-1.1-Signed-off-by: Roy Sutton roy.sutton@lge.com
> Cherry-pick ENYO-2709 and ENYO-3242 into 2.6.4-rc.1

- src/ProgressBar/ProgressBar.js
> ENYO-3244: Use generic setters and enhance guards.

- css/moonstone-variables-dark.less
- css/moonstone-variables-light.less
- css/moonstone-variables.less
- src/Input/Input.less
- src/InputDecorator/InputDecorator.js
- src/InputDecorator/InputDecorator.less
- src/TextArea/TextArea.less
> PLAT-16501: Adding input validation.

- src/Panels/Panels.js
Issue:
App close button is a child of panels but not panel. So, when it is
looking for nearest neighbor from input of header, it fails to find app
close button.
Fix:
- App close button should be considered as a child of Panel. So, added
more condition on getSpotlightTarget.
- Added handling for spotlight up/down just like left/right and
refactored handle5wayForAppCloseButton as a common code.
> ENYO-3228: Force move focus to app close button on right key from input

- src/ListActions/ListActions.less
Changes from https://github.com/enyojs/moonstone/pull/2771.
> ENYO-3232 (2.6.4-rc.1)

- src/Header/Header.less
- src/ListActions/ListActions.js
> ENYO-3255: Reset all direction classes added for direction adjustment

- src/DatePicker/DatePicker.js
- src/DateTimePickerBase/DateTimePickerBase.js
- src/TimePicker/TimePicker.js
Changes from https://github.com/enyojs/moonstone/pull/2736.
> ENYO-3142 (2.6.4-rc.1)

- src/ContextualPopup/ContextualPopup.js
- src/Popup/Popup.js
Changes from https://github.com/enyojs/moonstone/pull/2707.
> PLAT-16199 (2.6.4-rc.1)

- src/VideoPlayer/VideoPlayer.js
Enyo-DCO-1.1-Signed-off-by: Roy Sutton roy.sutton@lge.com
> ENYO-3291 Fix documentation of infoComponents type

- css/moonstone-rules.less
Enyo-DCO-1.1-Signed-off-by: Roy Sutton roy.sutton@lge.com
> ENYO-3294 Allow spotlight color in neutral theme

- css/moonstone-rules.less
Changes from https://github.com/enyojs/moonstone/pull/2808.
> ENYO-3294 (2.6.4-rc.2)

- src/Slider/Slider.js
- src/Slider/Slider.less
Changes from https://github.com/enyojs/moonstone/pull/2728.
> PLAT-15388 (2.6.3-rc.3)

- src/SimplePicker/SimplePicker.js
According to accessibility UX changes, change simplePicker's hint message.
https://jira2.lgsvl.com/browse/ENYO-3318
> ENYO-3318: Change audio guidance string in SimplePicker

- src/ContextualPopup/ContextualPopup.js
- src/Popup/Popup.js
- src/Tooltip/Tooltip.js
Issue
: Read sequence is not match to UX Guide
Fix
: Change read sequence at Popup, Contexture Popup
> ENYO-3260 : Change audio guidance read sequence

- src/SimplePicker/SimplePicker.js
Issue:
There is no generic way to do this by application side.
Fix:
Bind selected.accessibilityLabel in ariaObserver.
> ENYO-3372: Support a11yLabel for SimplePicker

- src/InputDecorator/InputDecorator.js
Prevent reading a invalid message when tooltip is shown in range input
https://jira2.lgsvl.com/browse/PLAT-20930
Change-Id: I4f3b95186e5b3629b1e423bcfda5e34e9b1f3347
> PLAT-20930: Prevent reading a invalid tooltip message.

- src/ContextualPopup/ContextualPopup.less
Percentage position makes unwanted location of arrow.
I found exact number of position and assigned.
> ENYO-3394: Set fixed position to arrow of contextual popup

- src/Dialog/Dialog.js
- src/Dialog/Dialog.less
- src/Popup/Popup.less
Revert client position to right side of title.
Revert divider and set default showing as true.
Revert padding and margin.
Enyo-DCO-Signed-off-by: Kunmyon Choi (kunmyon.choi@lge.com)
> ENYO-3396: Revert dialog layout

- css/moonstone-rules.less
Changes from https://github.com/enyojs/moonstone/pull/2869.
> PLAT-23335: Manually setting RI in CSS is no longer necessary

- src/ExpandableInput/ExpandableInput.js
Changes from https://github.com/enyojs/moonstone/pull/2850.
> PLAT-21870 (2.6.3-rc.11.s)

- css/moonstone-variables-dark.less
- css/moonstone-variables-light.less
- src/Spinner/Spinner.less
Set Spinner text color as white on dark background.
Set Spinner text color as dark gray on transparent background.
> ENYO-3429: Fix spinner text color on neutral theme

- css/moonstone-spacing.less
- src/ListActions/ListActions.js
In photo&video app case, arrow of contextualPopup(ListActions) has wrong position.
It is occurred when it use with IconButton. There are 2 problems.
First, in appliation side, app uses additional components block. So, 'moon-hspacing' of header clients is overrided.
Secondly, in framework side, 'moon-hspacing' does not cover the tooltip-decorator case.
It is fixed that case about 'tooltip-decorator' is added. Also, first-cheild of decorator has margin 0.
Moreover, It is added code which can cover the case about that 'hspacing' has contact with another 'hspacing'.
ENYO-3428 ListActions: arrow position is wrong when it use with IconButton
> ENYO-3428 ListActions: arrow position is wrong when it use with IconButton

- src/ScrollStrategy/ScrollStrategy.js
We got stuck in some scenario due to there is in-valid condition in
while statement. We fix in-valid condition and add guard condition
to avoid excpetional cases.
> ENYO-3437: Correct to corresponding condition and add guard condition

- src/NewDataList/NewDataList.js
Changes from https://github.com/enyojs/moonstone/pull/2894.
> PLAT-23893: Fix touch issue with NewDataList

- src/Scroller/Scroller.js
Changes from https://github.com/enyojs/moonstone/pull/2897.
> PLAT-21871:Fix touch issue with ListActions

- css/moonstone-variables.less
- src/Notification/Notification.js
- src/Notification/Notification.less
There were changes on style of Notification control.
I adjusted CSS to meet latest GUI redlines.
> ENYO-3446: CSS adjustment

- src/ListActions/ListActions.js
Added method for re-arraging position of popup in ListActions.
ENYO-3442 ListActions: need to update when activator position is changed
> ENYO-3442 ListActions: need to update when activator position is changed

- src/Notification/Notification.js
- src/Notification/Notification.less
Floating numbers on bounds caused several issues relate to rendering issues especially making blurred text.
I added new feature to enable above feature by handy option.
> ENYO-3473: Add new feature for auto position adjustment

- css/moonstone-variables.less
- src/Notification/Notification.js
- src/Notification/Notification.less
Adjust position on handleResize instead of rendered.
This change will make showingChanged call handleResize on show.
> ENYO-3473: Notification: text is rendered unclearly

- src/LightPanels/LightPanel.js
> Revert "ENYO-3467: Block _spotNearestToPointer while LightPanel is in transition"

- css/moonstone-text.less
- css/moonstone-variables.less
- src/Notification/Notification.js
- src/Notification/Notification.less
- src/Notification/package.json
Adds the `Notification` component from 2.6.4.
Issue: PLAT-28511
> Adds Notification component

- src/Notification/Notification.less
Change text align from center to left (right for RTL)
> ENYO-3615: Left align Notification popup text (right for RTL)

- css/moonstone-variables-bno.less
- src/LabeledTextItem/LabeledTextItem.less
Adding B&O theme file to support focus color.
> ENYO-3617: Adding B&O theme file
