enyojs/moonstone

samples/package.js
Cherry-picking changes from https://github.com/enyojs/moonstone/pull/1751 into `2.5.1-release`, creating a PR for tracking purposes.
=> ENYO-726: Adding fix for ENYO-437 (2.5.1.1)

source/MoonScrollStrategy.js
There can be instances where a paging control becomes disabled, and the corresponding and opposite paging control (which was the last spotted control) has not yet been enabled, causing Spotlight focus to move to the first child of the root.
We ensure that the to-be-enabled paging controls are enabled first, so that Spotlight can still spot the opposite (and last spotted) paging control when the currently spotted paging control is disabled. Additionally, we revert the change from https://github.com/enyojs/moonstone/pull/1827 as it is not necessary anymore.
Let me know if there are any performance concerns about sorting a 4-item array for each invocation of `updatePagingControlState`.
=> ENYO-592: Enable all to-be-enabled paging controls first.

source/Marquee.js
Cherry-picking the changes from https://github.com/enyojs/moonstone/pull/1864 into `2.5-gordon`, creating a PR for tracking purposes.
Note: This change is even more helpful for `2.5-gordon` as the lack of layers results in a number of additional repaints, so we want to minimize any unnecessary animation.
=> ENYO-696 (2.5-gordon)

css/Dialog.less, css/moonstone-dark.css, css/moonstone-light.css, source/Dialog.js
Issue:
moon.Dialog is layout title and client buttons with Fittable.
If developer dynamically change button showing status, then button will not be aligned on right side because the client width is fixed by fittable on render time.
Fix:
Remove fittable on Dialog and apply float to position client area.
=> ENYO-737: moon.Dialog client area layout by float not Fittable

css/Dialog.less, css/moonstone-dark.css, css/moonstone-light.css, source/Dialog.js
Cherry-picking the changes from https://github.com/enyojs/moonstone/pull/1889/files into `master`, creating a PR for tracking purposes.
Issue:
moon.Dialog is layout title and client buttons with Fittable.
If developer dynamically change button showing status, then button will not be aligned on right side because the client width is fixed by fittable on render time.
Fix:
Remove fittable on Dialog and apply float to position client area.
=> ENYO-737: moon.Dialog client area layout by float not Fittable (master)

source/SimplePicker.js
We had previously removed the call to `selectedIndexChanged` in `create` to prevent calling this method twice, in making this fix: https://github.com/enyojs/moonstone/commit/1a1ab6. This resulted in any `moon.SimplePicker` being set to an initial value that did not correspond to the first item to display an animation upon initial load.
Because we do not yet have a comprehensive fix for the rounding issue with transforms, we re-add the call to `selectedIndexChanged`.
For `moon.SimplePicker` controls with a high number of items (i.e. `moon.Calendar`), an animation will still be seen as we are necessarily adjusting the position via the original fix, but this change resolves the issue for the majority of cases.
=> ENYO-752: Set position of initial value via transform.

source/Marquee.js
`_marquee_calcDistance` expects a valid node to measure its natural and clipped dimensions. In cases where the control hasn't been generated but a marquee has been requested (e.g. an onRequestMarqueeStart event waterfalled down from a containing contro), this measurement fails.
Prevent starting marquee when the control hasn't been generated
=> Fixes ENYO-723

samples/DataGridListSample.js
We have made some updates to the selection state of `enyo.DataRepeater`, specifically introducing the `selectionType` property, via https://github.com/enyojs/enyo/pull/957.
The DataGridListSample has been updated to utilize the new `selectionType` property.
=> ENYO-643: Update sample to utilize "selectionType" property.

css/moonstone-dark.css, css/moonstone-light.css
With the change from https://github.com/enyojs/enyo/pull/994, we are limiting the number of decimal places in our converted measurements, necessitating a regeneration of the CSS.
The CSS has been regenerated. I went through the samples and didn't notice any adverse effects from slightly less fractional digits.
Travis will fail until https://github.com/enyojs/enyo/pull/994 has been merged and the build is rerun.
=> ENYO-722: Re-generate CSS with the appropriate amount of measurement precision.

source/Panels.js
Cherry-picking the changes from https://github.com/enyojs/moonstone/pull/1887 into `master`, creating a PR for tracking purposes.
Note: We also removed the changes from https://github.com/enyojs/moonstone/pull/1794 as part of resolving a merge conflict - these were deemed to no longer be necessary due to the refactoring of `moon.Panels`.
=> ENYO-719 (master)

css/Header.less, css/moonstone-dark.css, css/moonstone-light.css
Tooltips on buttons in Header's `headerComponents` area were clipped by the panel body because of the `z-index` change to it introduced by PR #1852.
Remove an unnecessary `z-index` from `.moon-header-client`.
=> Fixes ENYO-783

source/SimplePicker.js
SimplePicker fires its onChange event on it rendered instead of when, you know, it changes.
With ENYO-736 changing measurements to be multiples of 3, the original
logic for SimplePicker is effective so reverting the additional logic
to deal with subpixel measurements which cleans things up and removes
the trigger for onChange at render time.
=> Fixes ENYO-800

samples/ItemSample.js
The `ItemSample` had images that did not appear correctly in HD resolutions.
Utilize our new multi-res hash for the `src` property of our images. Additionally, made a few measurement corrections for the image sizes in FHD resolution as they had been previously been too wide.
=> ENYO-796: Utilize multi-res image hash for Item sample.

source/Header.js, source/Panel.js
When changing the type of a `moon.Header` where the client space changes, this width is not being recalculated and the title width is not being adjusted, resulting in overlap.
We call `adjustTitleWidth` whenever the `type` changes, after we have been generated (to not interfere with the logic in `rendered`). Additionally, the call to `adjustTitleWidth` from `moon.Panel` is no longer necessary and has been removed.
=> ENYO-799: Adjust title width when header type changes.

samples/ObjectActionVerticalTypeSample.js
The `ObjectActionVerticalTypeSample` displayed actions not centered on the images.
We utilize the multi-resolution image source hash for the images to display the appropriate image size for the given resolution.
=> ENYO-810: Utilize multi-res source hash for images.

samples/ImageBadgeSample.js, source/ImageMultiRes.js
`moon.ImageMultiRes` had the `moon-image` class applied, which resulted in the class being applied to both this control and its parent control `moon.Image`, resulting in the margin amount being compounded.
We update the images to use the multi-res hash and change the class name to `moon-image-multires`.
=> ENYO-811: Use multi-res hash for image sources, update classname for moon.ImageMultiRes.

samples/ItemSample.js
In HD resolutions, the fourth image in the sample displays the text `Item 3`. This is a regression from https://github.com/enyojs/moonstone/pull/1909 due to over-aggressive copy/paste. I take solace in being the one to discover my own mistake.
Correct the text to display `Item 4` in these cases.
=> ENYO-829: Correct typo for HD resolution.

source/Panels.js
Default value for `transitioning` is not defined on moon.Panels so calls to `isTransitioning()` returns `undefined` instead of a boolean.
Set the default value of `transitioning` to `false` on the kind
Regression from ENYO-719 (PR #1887)
=> Fixes ENYO-819

css/FormCheckbox.less, css/moonstone-dark.css, css/moonstone-light.css
Issue:
Form check box text color is gray when it is used in popup
Fix:
Change color when form check box is used under moon-neutral css.
=> ENYO-857: moon.FormCheckbox text color is wrong when used in moon.Popup

css/Button.less, css/ChannelInfo.less, css/Drawers.less, css/Icon.less, css/ImageItem.less, css/InputDecorator.less, css/ListActions.less, css/ProgressBar.less, css/VideoControlInline.less, css/moonstone-dark.css, css/moonstone-light.css
The maximum width of `moon.Button` is currently 302px, which is not a multiple of 3.
We adjust the maximum width of `moon.Button`, along with some other measurement tweaks aimed to promote saner measurement values.
=> ENYO-828: Adjust maximum button width, other measurement tweaks.

css/Marquee.less, css/moonstone-dark.css, css/moonstone-light.css
The `scrollWidth` of a `moon.Marquee` can have an incorrect value of 0.
This is due to the `display:inline` rule being applied to the `moon.Marquee` control. We add a comment about overriding this rule. Credit to @Djspaceg for the fix.
=> ENYO-805: Prevent incorrect marquee distance calculation.

source/Marquee.js
setTimeout(fn, 0) in _marquee_addAnimationStyles is executing before the browser has rendered/repainted/something? the newly created marqueeText node. As a result, it already has the transform/left style applied so the animation is skipped and it's just painted at it's final position.
Increase the timeout to apply the final style value to marquee text
=> Fixes ENYO-771

samples/package.js
There is a stale reference to `Sample.css` and `Sample.html` in the `package.js` for the sample folder, which can cause build issues.
The stale references have been removed.
=> ENYO-888: Remove stale reference to Sample.css

light-package.js
Light theme app such as Settings are not able to find moon.config.accelerate on app launch.
Add init.js into light-package.js
=> ENYO-904: light-package.js doesn't include init.js

samples/.htaccess, samples/Sample.html
Cherry-picking the changes from https://github.com/enyojs/moonstone/pull/1957 into `2.5-upkeep`, creating a PR for tracking purposes.
=> Added redirection code to catch samples being loaded with the old-style ... (2.5)

css/Dialog.less, css/moonstone-dark.css, css/moonstone-light.css, source/Dialog.js
Regression of https://github.com/enyojs/moonstone/pull/1889
After change the client layout to be float right, the divider area can be also floated abound by buttons.
Adding min-height on Title area of Dialog popup so divider is not collapsed with client buttons.
=> ENYO-905: Adding min-height on Dialog Title Area

css/moonstone-dark.css, css/moonstone-light.css, css/moonstone-variables.less, samples/DataGridListSample.js
Due to some measurement tweaks made to minimize rounding issues, the previously set height of the "Selection" popup in the DataGridListSample (via the `moon-6v` class) caused the last item to be partially obscured.
We remove the `moon-6v` class and allow the popup to be sized to the natural height of its contents. Additionally, we correct the height of the grid rows to more closely match the adjustments we have made throughout.
=> ENYO-891: Allow popup to be sized to the natural height of contents.

source/DatePicker.js, source/DateTimePickerBase.js
ilib's locale can be set to the wrong value when using `enyo.updateLocale` where there are multiple date/time pickers. This was exposed by another issue, both of which have been addressed.
This was a seemingly minor issue that pointed to larger problems. In the `DatePickerSample`, changing the locale resulted in the disabled picker becoming valued. Technically a regression from https://github.com/enyojs/moonstone/pull/1800, the change in that PR was necessary to properly change locales without affecting other samples (i.e. via Sampler). This pointed to the fact that whenever we receive the `onlocalechange` signal (in this case triggered by a call to `enyo.updateLocale`), if there are multiple `moon.DatePicker` or `moon.TimePicker` controls, the locale of ilib would be set to the …
=> ENYO-892: Prevent unnecessary re-setting of ilib locale.

source/Panels.js
There was a delay when moving Spotlight focus between joined panels.
We ensure that we only execute the extensive animation cycle (involving `enyo.Animator`) when an arrangement is required, so the case of joined panels should be excluded. Additionally, we store the value of `shouldAnimate` once we have calculated it for a given index change, so that it does not need to be recalculated when the `indexChanged` method of `enyo.Panels` is run.
This PR is dependent on https://github.com/enyojs/layout/pull/117
=> ENYO-890: Prevent running animation when no arrangement is needed.

samples/MarqueeSample.css, samples/MarqueeSample.js, source/Marquee.js
On app change state between BG and FG, div which is under cursor is not getting onleave event.
While marquee is flow on hover, it is not stop because it is not getting onleave event when app  goes to BG.
- Add blur on windowEvents array to handle on dispatcher feature. (Core)
- Remember last hovered marqueeSupport control on global variable. (Marquee)
- Call onleave event handler of last hovered marqueeSupport control when app is getting onblur event. (Marquee)
=> ENYO-923: Stop marquee when window throw blur event

css/Dialog.less, css/moonstone-dark.css, css/moonstone-light.css
After some tweaks to the layout of `moon.Dialog`, the position of the client area required some adjustment.
We adjust the position of the client area such that it is higher above the divider.
=> ENYO-976: Adjust client position of Dialog.

source/VideoPlayer.js, source/VideoTransportSlider.js
moon.VideoPlayer has a remoteKeyHandler which is calling this.jumpToStart() when 'stop' button is pressed.
But, jumpToStart is calling play when it is called while it is playing. So, it's play again after change current time to 0 and paused.
- Set this._isPlaying as false before calling  this.jumpToStart() to block calling play.
- Call this.sendFeedback('Stop'); after calling this.jumpToStart() to change feedback text from 'paused' to 'stop'.
=> ENYO-875: moon.VideoPlayer remoteKey 'stop' is not stop playing

css/SelectionOverlaySupport.less, css/moonstone-dark.css, css/moonstone-light.css, source/SelectionOverlaySupport.js
* SelectionOverlaySupport only needs the original icon it had, and no additional modifications.
* The CSS is simplified to provide support for the following states: normal nothing visible, selectable/unselected, and selectable+selected.
* With only one element in the scrim, the CSS and DOM become much simpler, we only need to set the general sizing, the unselected colors, and the selected colors.
=> ENYO-576: Reworked SelectionOverlay CSS to be more efficient.

css/moonstone-dark.css, css/moonstone-light.css, css/moonstone-variables.less
The value of `@moon-body-font-size` was changed from `26px` to `24px` during the changes to support resolution-independence. This change made the size of the text too small for certain controls.
In this instance, changing the value to the nearest multiple of 6 was too great of a change, so we instead change this value to `27px`.
=> ENYO-1011: Adjust font-size for moon-body.

css/CheckboxItem.less, css/moonstone-dark.css, css/moonstone-light.css
In a previous fix (https://github.com/enyojs/moonstone/pull/796), we had added a rule to add padding for `moon.CheckboxItem` to correct an aberration observed only the TV. Due to a WebKit issue where padding would not be properly measured when determining the `scrollWidth` value in RTL mode, this caused the initial measurement of the distance to marquee to be incorrect, and in particular, to be zero in this case, causing the content to not marquee at all.
I've created a fiddle (actually an old one I had created a while back as we had run into this issue previously: http://jsfiddle.net/aarontam/pp2rw/) that demonstrates the WebKit issue. Meanwhile, while this issue is being investigated, the now-unnecessary rule has been removed and I've verified the original issue does not occur with this …
=> ENYO-907: Remove unnecessary padding.

source/ContextualPopup.js
Some private properties are set by fixed number
Set private properties as resolution independent by using moon.riScale()
=> ENYO-980: Lite: Fixed size was set in moon.ContextualPopup

source/DataGridList.js
moon.DataGridList showing blank page when empty and add collection while scrolling.
This regression is introduced when we remove duplicated page generation https://github.com/enyojs/moonstone/pull/1868/files#diff-ad39c65132790ca5d3df3e181f58d645R115
Originally, scroll strategy was stop scrolling when collection empty.
Because, we called scroller resize on DataGridList refresh.
So, add refresh function back to DataGridList and checked page generation is still not duplicated.
=> ENYO-1026: Call scroller resize on moon.DataGridList refresh

source/DataGridList.js
Cherry-picking the changes from https://github.com/enyojs/moonstone/pull/2001 into `release-2.5.3-pre.17.t`, creating a PR for tracking purposes.
=> ENYO-1026 (release-2.5.3-pre.17.t)

source/History.js
The moon.History singleton was doing some initialization in its
create() method that depended on the presence of webOS.js. This
was working fine in unminified app source (and probably in the
container as well), but not in deployed app source, because the
singleton was being created before webOS.js could be loaded.
To address this issue, we move the initialization code out of
create() and into a separate init() method that we invoke in a
call to enyo.ready().
=> ENYO-1030: Moving moon.History initialization out of create()

source/Slider.js
Previously, only the end value was clamped which allowed the slider to
animate from an invalid value.
Clamp start of Slider.animateTo
=> Fixes ENYO-1139

source/VideoTransportSlider.js
If the pointer is enters the slider tap area while the slider is disabled, future pointer movements do not correctly display the preview because preview mode was not enabled when the pointer entered.
Since displaying the preview is also guarded by a disabled check, we
can always enable preview mode when entering the tap area so that if
the slider is enabled while the pointer is still within the tap area,
future pointer movements will correctly update the preview display.
=> Fixes BHV-23301

samples/manifest-light.json, samples/manifest.json
We had been making sample additions here and there but had forgotten to keep the Moonstone manifests in sync.
The manifests have been updated to reflect the current state of the samples. Wanted to take care of this before it became more outdated and/or it was forgotten again.
=> ENYO-1035: Add missing samples to manifest.

samples/PanelsVideoPlayerSample.js, samples/VideoPlayerSample.js
The Inline Video Player no longer supports the OGG video format (Bunny and Counter video). The Sintel video is the only functional video that plays back.
verify and fix paths to w3 media files
Enyo-DCO-1.1-Signed-off-by: Krishna Rangarajan <krishna.rangarajan@lge.com>
=> ENYO-1100: Replace existing OGG videos in the Panels Video Player sample

css/ToggleSwitch.less, css/moonstone-dark.css, css/moonstone-light.css
The ghost checkmarks and moon.Icon refactor interfered with the inherited styles of the ToggleSwitch.
=> ENYO-1226: ToggleItem is now the correct color on spotlight and animation restored

source/ExpandableInput.js
When initiating a drag on the `moon.InputDecorator` control, with the VKB visible, the drag ends due to what seems to be a `mouseout` event being fired. This causes the `moon.ExpandableInput` to collapse in response to an `onSpotlightBlur` event being triggered by the `mouseout`, in addition to the `moon.InputDecorator` being focused in response to an `onSpotlightSelect`, also due to the `mouseout`.
This fix attempts to address this behavior by preventing the collapse of the `moon.ExpandableInput` in this situation by guarding against collapsing when the previous event was `dragstart` or `drag`. Also took the liberty of converting parameter names to remove the `in` prefix.
=> ENYO-1251: Prevent unnecessary collapsing of input.

css/CheckboxItem.less, css/moonstone-dark.css, css/moonstone-light.css
In RTL mode, for a `moon.CheckboxItem` control, the `moon.Checkbox` control overlaps with the client area.
We correct the positioning of the `moon.Checkbox` control by changing `left:@moon-spotlight-outset + 3` to `left:@moon-spotlight-outset - 3`, to match the rule we have for the `right` property.
=> ENYO-817: Correct positioning of checkbox in RTL.

source/MoonScrollStrategy.js
When there is an expandable control that is at the edge of a scrollable region which currently does not require scrolling, expanding the control does not result in the control being properly scrolled into view.
There was an ordering issue where we were first determining whether we needed to scroll, before the bounds were updated. This change made it into 2.3.x, but not in anything after (2.4.x, 2.5.x, 2.6.x).
=> ENYO-1033: Scroll into view expanded controls at the edge of the scrollable region.

source/DataList.js
Issue:
If the moon.datalist having a long list and while scrolling this list, if the collection is chaned then the dalalist items are not displayed.
Fix:
Add refresh() function into DataList and Stop the DataList scroller to remove the scrolling if the collection is changed
=> ENYO-1289: Stop datalist scroller on collection changed

css/Button-color.less, css/FormCheckbox-color.less, css/Header-color.less, css/Icon-color.less, css/IconButton-color.less, css/Item-color.less, css/Panel-color.less, css/Panels-color.less, css/Spinner-color.less, css/moonstone-dark.css, css/moonstone-dark.less, css/moonstone-light.css, css/moonstone-light.less, css/moonstone-rules-color.less, css/moonstone-text-color.less
Simply apply `moon-theme-light` or `moon-theme-dark` to any container and have all child controls use the indicated theme.
(This initial version is an abbreviated set of controls specifically for Settings)
=> ENYO-458: Added theme classes to redefine any container to any theme.

css/Calendar.less, css/ChannelInfo.less, css/Dialog.less, css/Header.less, css/Item.less, css/ListActions.less, css/VideoInfoHeader.less, css/moonstone-dark.css, css/moonstone-light.css, css/moonstone-rules.less, css/moonstone-text.less, css/moonstone-variables-dark.less, css/moonstone-variables-light.less, css/moonstone-variables.less, source/Header.js
* Renamed the `.moon-sub-header-text-base` to `.moon-text-base` to be more geneic and universal. It now also respects the standard text color if none is provided.
* Rearranged some rules for better, more logical inheritance.
* Reassigned some static strings to logical related variables, not just because they have the same value, but because the two elements should have matching styles.
* Header now uses better class names for its subtitles.
=> ENYO-1146: Reassigned font sizes

source/VideoTransportSlider.js
The initial size of popupLabel in VideoTransportSlider is longer than the runtime popupLabel
moon.VideoFeedback isn't showing at first time in VideoTransportSlider and VideoPlayer but it has margin value
set VideoFeedback showing false for removing unnecessary margin
This is copy of https://github.com/enyojs/moonstone/pull/2036 for 2.5-upkeep
Enyo-DCO-1.1-Signed-off-by: Sungbae Cho (sb.cho@lge.com)
=> BHV-24015: set showing false for removing unnecessary margin

source/ContextualPopup.js, source/ContextualPopupDecorator.js
Issue
-------
After pressing back key in ContexualPopup, spotlight focus does not return to origin.
Cause
--------
When popup is opened, contents of popup had spotlight focus. 
But back key hide popup without spotlight focusing, so spotlight focus lost its way and back to container.
Fix
----
When popup is closed with back key, trigger onRequestSpot event to focus contextualPopup button.
=> ENYO-965 Restore spotlight focus to contextual popup

source/SelectionOverlaySupport.js
In RTL mode, the selection overlay icon is not positioned in the center. This is due to the fact that we are setting different positioning based on directionality, but are not accounting for this when setting the `translateX` value to adjust the selection overlay icon back to the center.
We could add a CSS rule to set `translateX(50%)` when in RTL mode, but it seemed more straightforward to eliminate unnecessary RTL handling where possible, so we always absolutely position the selection overlay icon utilizing the `left` property, as we are only concerned with the icon being centered.
=> ENYO-1137: Correct positioning of selection overlay.

source/BreadcrumbArranger.js, source/DataGridList.js, source/Header.js, source/ListActions.js, source/Slider.js
We had initially created the resolution-independent support methods in the moon namespace and have since moved these methods to the enyo namespace.
Convert calls to `moon.ri.scale` to `enyo.ri.scale`.
=> ENYO-1287: Transition from moon.ri.scale to enyo.ri.scale.

source/Scroller.js
New UX : Add the ability to page (scroll) using PG Up/Down on the remote
Added {{handlePageUpDownKey}} property and make it set to true when the pointer is on the scroller or focus on the scroller. And If user press Page Up/Down key, scroller calls {{paginate}} function.
Enyo-DCO-1.1-Signed-off-by: Sungbae Cho (sb.cho@lge.com)
=> ENYO-509:Add the abilit to page scroll using PG Up/Down key

css/Item.less, css/ItemOverlay.less, css/moonstone-dark.css, css/moonstone-dark.less, css/moonstone-light.css, css/moonstone-light.less, css/moonstone-mixins.less
The recent addition of the `moon.ItemOverlay` exposed an issue with `moon.Icon` controls nested inside `moon.Item` controls. In particular, the tap area of `moon.Icon` extended beyond the outer limits of `moon.Item`, causing there to be a non-zero `scrollWidth` for `moon.Item`. The result was that this control would unnecessarily be added to the marquee waitlist, but would never be popped as our originating control for the `onMarqueeEnded` event would be the `moon.MarqueeText` control and not the `moon.Item` control; this prevented the marquee from restarting.
I went with the direction of adjusting the tap area to fit within `moon.Item`. This involved adjusting the `right` and `left` values accordingly (both are adjusted to the same value to preserve the position of the icon), based on …
=> ENYO-937: Adjust tap area for moon.Icon controls in moon.Item controls.

source/History.js
Issue
------
Pressing back key make it back to previous page in browser
Cause
-------
history.back() call without pushed history state will back to previous page. Natural behavior of history object.
Fix
----
Add a guidance state to prevent to back to previous page
updated from https://github.com/enyojs/moonstone/pull/2000 
=> ENYO-964 Prevent to back previous page in browser

css/VideoPlayer.less, css/moonstone-dark.css, css/moonstone-light.css, samples/VideoPlayerSample.js, source/VideoPlayer.js
There was a Q issue about ignoring tap events while the video is loading. @mediachild felt that ignoring the tap event before the video starts is reasonable behavior, so opening a PR to add this behavior to the framework.
Similar to the technique used in Panels.less, add an :after scrim which blocks the tap while a particular class ('spinner-showing') is applied
=> ENYO-1107:  ignoring tap events before video starts

source/IntegerPicker.js
We were currently scrolling into place the item corresponding to the current value of `moon.IntegerPicker`, when unhiding the picker control. This was originally done to scroll into view the appropriate item, if the value had been changed while the picker control was hidden. What is occurring in this case is that the scroll position is incorrect after unhiding because we are not providing a "previous" item to scroll from (which had previously occupied the space above the current item), when scrolling to the current item.
One way to fix this would be to brute-force refresh the scroll bounds in this scenario where we are unhiding and subsequently scrolling to the current item. But to avoid any unnecessary scroll bounds calculations, I have instead modified the conditional such that we guard …
=> ENYO-1217: Only scroll to value if node does not exist.

source/ContextualPopup.js, source/ContextualPopupDecorator.js
Issue raises because, handling events is not done properly. To close a
popup 2 events are being used. One from popup, other from popup
activator button's activated event. Dependency is removed on
"activatate" event. This fixes one more issue of popup not opening.
Enyo-DCO-1.1-Signed-off-by: Rajyavardhan P<rajyavardhan.p@lge.com>
=> ENYO-712-Unspottable popup does not dismiss on Enter fixed

source/DatePicker.js
At creation time of Date Picker, *value* is set to null so iLib date object cannot be instantiated from it. However picker calls iLib function to calculate maximum days by passing undefined values. Inside iLib API, there exist a code trying to manipulate undefined params and it causes undefined error.
Before calling iLib API to get **monthLength**, we'll check if parameters to be passed like **inYear** and **inMonth** have proper values.
Enyo-DCO-1.1-Signed-off-by: Hunkyo Jung <hunkyo.jung@lge.com>
=> ENYO-1335: Date Picker : Passing undefined params stops application

source/LightPanel.js
When used in conjunction with the view preloading mechanism, the client components of a `moon.LightPanel` can potentially be created multiple times.
A check has been added for the existence of client components, guarding against repeated creation of the components.
=> Clean-up post-transition logic.

source/Thumb.js
Cherry-picking the changes from https://github.com/enyojs/moonstone/pull/2067 into `2.5-upkeep`, creating a PR for tracking purposes.
=> ENYO-1368: Enlarge scroll thumb minimum height from 20 to 40 (2.5-upkeep)

source/Thumb.js
Cherry-picking the changes from https://github.com/enyojs/moonstone/pull/2075 into `2.6.0-pre.4-dev`, creating a PR for tracking purposes.
=> ENYO-1368: Enlarge scroll thumb minimum height from 20 to 40

css/VideoControlFullscreen.less, css/moonstone-dark.css, css/moonstone-light.css
##Issue
There was a Q issue about disabled imageIcon like rewind or fastFoward in videoPlayer.
If disabled rewind or fastFoward image Icon in videoPlayer is clicked, then it is affected by css and changes its color to red.
##FIx
It is needed to make css effective only when icon is not disabled.
To do this, I added ":not(.disabled)" in VideoControlFullscreen.less.
So, when an icon is disabled, the css does not affect disabled icon.
This is copy of #2069 for 2.5-upkeep
Enyo-DCO-1.1-Signed-off-by: Suhyung Lee suhyung2.lee@lge.com
=> ENYO-1438: make css of videoPlayer's iconButton like REW/FF be effective only when icon is enabled.

lib/History/History.js
Keeps moon.History from hooking the back button when historyAPI is disabled.
=> when disabling moon history, back button should function

lib/ScrollStrategy/ScrollStrategy.js
Cherry-picking the changes from https://github.com/enyojs/moonstone/pull/2099 into `2.6.0-dev`, creating a PR for tracking purposes.
=> ENYO-1138: Client area of scroller is shaking when expandable picker is hidden

lib/LightPanel/LightPanel.js
"Cherry-picking" changes to `moon.LightPanel` from `2.6.0-pre.4-dev` to `2.6.0-dev`. This PR is related to and dependent upon https://github.com/enyojs/enyo/pull/1140.
=> [2.6.0-pre.4-dev -> 2.6.0-dev] LightPanels updates and refinement.

source/moon-resolution.js
moon.ri.init() function needs a line for removing ScreenTypeOnBody
moon.ri.getScreenTypeObject always return old screenTypeObject if there is no parameter
added oldScreenType variable for for checking and removing old resolution classes.
and removed caching routine in getScreenTypeObject function.
Enyo-DCO-1.1-Signed-off-by: Sungbae Cho sb.cho@lge.com
=> ENYO-1441 : modify resolution update routine for removing old resolution classes

lib/IntegerPicker/IntegerPicker.js
Due to some optimizations in `ScrollMath` we are now calculating the `maxY` value from the current scroll bounds and clamping to that value for the amount of vertical scrolling. In the case of `moon.IntegerPicker`, there is only one item rendered initially, and so outdated scroll bounds are utilized when scrolling to the next value.
We now force a recalculation of the scroll boundaries when the flyweight repeater is re-rendered.
=> ENYO-1217: Update scroller boundaries when (re)rendering the repeater.

samples/ExpandablePickerSample.js, source/DayPicker.js, source/ExpandablePicker.js, source/package.js
There is a requirement for supporting string overlay on Expandable picker in Dreadlocks.
(Especially, it target expandable picker which can select day of the week and shows representative value )
For resolving the requirement, make a new kind which inherited from Expandable Picker and add features which are described in ENYO-519
This is copy of https://github.com/enyojs/moonstone/pull/1961
DCO-1.1-Signed-Off-By: Sungbae Cho sb.cho@lge.com
=> ENYO-519 : add moon.DayPicker component as a Dreadlocks UX requirements

lib/PagingControl/PagingControl.js
`enyo.bench()` was converted to `require('enyo/dev').bench()`
Should have been `require('enyo/utils').perfNow()`
=> Fixes ENYO-1537

css/moonstone-variables.less
The content inside the button extends beyond the curvature of the
button, which is a deviation from specs.
Padding of the button is increased to make content align with in the
curvature.
Enyo-DCO-1.1-Signed-off-by: Rajyavardhan P <rajyavardhan.p@lge.com>
=> ENYO-1332: adjusting the content inside button according to the specs

lib/InputDecorator/InputDecorator.less
The end radius of the input field (moon.InputDecorator) is not a proper half circle.
The border circle of the moon.InputDecorator is achieved by border-radius css property. The value of border-radius was 30px earlier and is been replaced by 1008px in solve this issue.
DCO-1.1-Signed-Off-By: Anish TD anish.td@lge.com
=> ENYO-1327: Radius is incorrect in the text Inputs

lib/TimePicker/TimePicker.js
There is a requirement to make bottom text of Time Picker be displayed optionally in Dreadlocks.
For the requirement, I added published property "bottomTextEnable" whose default value is true.
Also, I made changes in setupPickers func.
- "current" : creates both picker and bottomText -> "modified" : creates picker first and then only when bottomTextEnable is true, creates bottomText.
This is copy of #2082 for 2.6.0-dev
DCO-1.1-Signed-Off-By: Suhyung Lee suhyung2.lee@lge.com
=> ENYO-1311 : Time picker: make it optional to display bottom text (rank: 19)

lib/Slider/Slider.js
This issue is found on SmartShare app and we have DEV tracker issue.
In photo view, when trying zoom in or out with magic remote and trying input left or right key on normal remote, knob is moving beyond slider bar.
Step to reproduce
1. Open moon.Slider example,
2. with magic remote or mouse, focus on first slider and moving left or right and don't release magic remote or mouse.
3. with normal remote, press ok to enable selection. After that. you can release the magic remote or mouse. But if you do not release mouse or magic remote, you can reproduce better.
4. click left or right button, then you can see the disabled slider's knob is moving
The reason why the knob is moving by left or right key is the selection mode is enabled even if this.dragging is true.
So, If I does not release …
=> ENYO-1529: in moon.Slider, value of knob is changing by left or right key during draging status

lib/VideoTransportSlider/VideoTransportSlider.js
With the update in https://github.com/enyojs/moonstone/pull/2131, we added "jump increment" buttons to `moon.Slider`, which are enabled by default. We missed the fact that there is another control, `moon.VideoTransportSlider`, that subkinds `moon.Slider` and is not interested in these buttons. 
We now set `enableJumpIncrement` to `false` for `moon.VideoTransportSlider`.
=> ENYO-1653: Hide the jump increment slider buttons.

source/MoonScrollStrategy.js
Issue:
- getAbsoluteBounds right value was measured from the right edge before https://github.com/enyojs/enyo/commit/c1189eef1fb245badaa3ac9d22af930cda678183 commit.
- Now right value is measured from the left edge. So, controlBounds.right - absoluteBounds.right is negative value.
Fix:
- Reverse offsetLeft calculation to it can have positive value.
=> ENYO-1649: scrollToControl makes scroller shake on rtl case

source/DayPicker.js
can't represent weekend and weekday when user select all of weekday or weekand in some country (fa-IR, ku-Arab-IQ, and xx-IN)
* fa-IR :  firstDayOfWeek - 6, weekEndStart - 5, weekEndEnd - 5
* ku-Arab-IQ : firstDayOfWeek - 6, weekEndStart - 5, weekEndEnd - 6
* xx-IN :  firstDayOfWeek - 0, weekEndStart - 0, weekEndEnd - 0
update calculation routine to handle several countries case
Enyo-DCO-1.1-Signed-off-by: Sungbae Cho sb.cho@lge.com
=> ENYO-1660: update to handle several countries case

lib/DayPicker/DayPicker.js, lib/DayPicker/package.json, lib/ExpandablePicker/ExpandablePicker.js
There is a requirement for supporting string overlay on Expandable picker in Dreadlocks.
(Especially, it target expandable picker which can select day of the week and shows representative value )
For resolving the requirement, make a new kind which inherited from Expandable Picker and add features which are described in ENYO-1563
(* This pr is converted from https://github.com/enyojs/moonstone/pull/1961)
DCO-1.1-Signed-Off-By: Sungbae Cho sb.cho@lge.com
=> ENYO-1563 : add moon.DayPicker component as a Dreadlocks UX requirements

source/MoonScrollStrategy.js
Scroller contents with leading or trailing margins may not be included in the size calculations throwing off scrolling at the edges.
Add pseudo elements to scroller to force block formatting context
=> Fixes ENYO-1542

lib/ExpandablePicker/ExpandablePicker.js
The selectAndClose() get called if the isDrawerRendered property true. But in initially isDrawerRendered property was became false in the render function as the drawer.renderOnShow is always true. This cause the issue that in activated function this.startJob won't fire as the this.isDrawerRendered is false.
Instead of using drawer.renderOnShow, use this.getOpen() to identify whether the drawer is already opened and set isDrawerRendered property true in such cases will solve the issue.
DCO-1.1-Signed-Off-By: Anish TD anish.td@lge.com
=> ENYO-1443: ExpandablePicker: Pre-Expanded Picker Does Not Collapse Initially after Selection

source/Marquee.js
issue. Marquee Text is ellipsis but doesn't roll when content has same length with div width
fix. when rendered, request the marquee to calculate it's distance.  Remove the ellipse formatting if the distance to move is 0.
=> Enyo 1285 derekanderson

lib/Marquee/Marquee.js
issue. Marquee Text is ellipsis but doesn't roll when content has same length with div width
fix. when rendered, request the marquee to calculate it's distance. Remove the ellipse formatting if the distance to move is 0.
Enyo-DCO-1.1-Signed-off-by: Derek Anderson derek.anderson@lge.com
=> ENYO-1285: text ellipse on marquee

source/Marquee.js
This issue is found by settings app developer.
In settings app, marquee does not flow entirely with certain language at first time.
From second time, marquee flows entirely.
Step to reproduce:
1. change language by below luna command
luna-send -n 1 luna://com.webos.settingsservice/setSystemSettings '{"settings": {"localeInfo": {"locales":
{ "UI": "ar-SA" }
} } }'
2. go Settings -> Picture -> Aspect Ratio -> cinema zoom
3. focus on last item ( I attached the image)
Problem :
marqueeText does not flowed entirely
Expected :
marqueeText should flow entirely (till end of context)
I added line to update distance in '_marquee_startAnimation' function.
The reason why marqueeText does not flow entirely at first time is the distance which will be used in …
=> ENYO-1579 : Marquee distance is not properly updated at first time, so marquee does not flow entirely

lib/Marquee/Marquee.js
Changes from https://github.com/enyojs/moonstone/pull/2134.
=> ENYO-1621: Marquee distance is not properly updated at first time, so marquee does not flow entirely

source/Marquee.js
Issue. 
Hidden Marquees would not update because the bounds of the box would be 0,0,0,0 when hidden. 
Solution.
Added a check to reflow for items that are re-rendered.
2.6.0-dev https://github.com/enyojs/moonstone/pull/2218
=> check on reflow, and only check visible items

lib/Marquee/Marquee.js
Issue.
Hidden Marquees would not update because the bounds of the box would be 0,0,0,0 when hidden.
Solution.
Added a check to reflow for items that are re-rendered.
Enyo-DCO-1.1-Signed-off-by: Derek Anderson derek.anderson@lge.com
2.5-upkeep https://github.com/enyojs/moonstone/pull/2217
=> calc on reflow, and only calc when visible on setContent

lib/History/History.js
Checks the appinfo.json for the disableBackHistoryAPI flag.
=> ENYO-1496: AppInfo-checking components in moon.History

lib/VideoPlayer/VideoPlayerAccessibilitySupport.js
The name of the playback control buttons are read differently from UX.
UX requirement is reading
"previous", "rewind", "play/pause", "fast forward", "next" on playback icon
The UX guideline is updated after applying accessibility on playback control buttons.  
Change accessibility label content with changed name of UX guideline ( UX_2016_webOS_Initial_Audio Guidance_v1.0.4_150618.pdf )
=> DRD-12481 : Change accessibility label content

source/Marquee.js
marquee text is clipped only, even if content should be ellipsis in expandable picker, drawer, OverlayText...
The reason why only clip is applied is we firstly cache the non-display control whose scrollWidth and getBoundingClientRect are zero as _marquee_distance.
We need to only cache the distance when controls are absoluty shown.
This is copy of #2251 for 2.5-upkeep
Enyo-DCO-1.1-Signed-off-by: Suhyung Lee suhyung.lee@lge.com
=> ENYO-1285 : Marquee Text is ellipsis on marquee

lib/DayPicker/DayPicker.js
=> ENYO-1945: Removed 'enyo.Signals' and require enyo/Signals

css/moonstone-variables.less, lib/Accordion/Accordion.less, lib/Checkbox/Checkbox.less, lib/CheckboxItem/CheckboxItem.less, lib/Dialog/Dialog.less, lib/Divider/Divider.less, lib/ExpandableListItem/ExpandableListItem.less, lib/ExpandablePicker/ExpandablePicker.less, lib/FormCheckbox/FormCheckbox.less, lib/Header/Header.less, lib/ImageItem/ImageItem.less, lib/Item/Item.less, lib/ItemOverlay/ItemOverlay.less, lib/LabeledTextItem/LabeledTextItem.less, lib/RadioItem/RadioItem.less, lib/SelectableItem/SelectableItem.less
These changes did not need to be locale-specific as they should not drastically alter the appearance of non-tall-glyph-locales.
Tested with the Thai tall glyph: `ฎิ์`
=> ENYO-1619: Adjusted heights of components to better support tall glyphs

lib/Checkbox/Checkbox.js, lib/CheckboxItem/CheckboxItem.js, lib/CheckboxItem/CheckboxItemAccessibilitySupport.js, lib/Icon/Icon.js
Apply accessibility on moonstone CheckboxItem. 
When CheckboxItem is focused, Only child checkbox is readout.
The CheckboxItem consists of checkbox and text item. When spotlight is focused on CheckboxItem, only child checkbox component is readout because CheckboxItem does not have checkbox role and aria-checked attribute.
Checkbox and Text Item are child component of CheckboxItem, so they do not need tabIndex and accessibility-related code and If CheckboxItem has accessibilityDisabled:true, their accessibilityDisabled value also should be true To implement this work, we added accessibilityDisabled attribute to each component source code.
In CheckboxItem, **accessibilityDisabled:true** is added to checkbox and text control regardless of accessibilityDisabled of CheckboxItem.
In Checkbox, …
=> ENYO-1687 : apply accessibility on moonstone checkboxItem

lib/Button/Button.less
* ContextualPopupButton now has the same active state appearance as grouped buttons.
* Removed redundant/excessive code cases (&.active, &.spotlight.pressed, etc)
* Setup all state rules to be either a child of :not(disabled) or [disabled], which will include more cases and be easier to understand what's going on.
* Simplified logic cases for combinations of translucency, spotlight, active, pressed, focused, etc.
=> ENYO-1870: Greatly simplified the logical structure and amount of rules for button

lib/SimpleIntegerPicker/SimpleIntegerPicker.js
Issue: When unit value is changed, its not getting reflected at picker's
value
Cause: value of picker (value + units) getting updated only when value
is changed, but it should update when unit too changed.
Fix: updating the picker's value when unit value change.
DCO-1.1-Signed-off-by: Srinivas V srinivas.v@lge.com
=> Enyo-960:[Moonstone]:ExpandableIntegerPicker is failed to set unit value

lib/Button/Button.js, lib/Button/ButtonAccessibilitySupport.js, lib/ToggleButton/ToggleButton.js, lib/ToggleButton/ToggleButtonAccessibilitySupport.js
Apply accessibility on moonstone ToggleButton
However, ToggleButton's child component has tabIndex, so we should remove it because ToggleButton already has button role and related aria attributes.
Thus, add **accessibilityDisabled:true** to moonstone Button because ToggleButton extends Button.
Should read out toggle status when the spotlight is focused to ToggleButton
ToggleButton requires press-and-release cycle to change their value.
To support readout toggle-status, we should add aria-pressed attribute to ToggleButton.
Add aria-pressed attribute to ToggleButton
Remove tablndex from Button using accessibilityDisabled API.
In addition, add aria-labelledby attribute because screen reader does not reads when child component has tabindex.
Enyo-DCO-1.1-Signed-off-by: Bongsub Kim …
=> ENYO-1688 : apply accessibility on moonstone ToggleButton

lib/LightPanel/LightPanel.js, lib/LightPanels/LightPanels.js
Based on the changes from https://github.com/enyojs/enyo/pull/1216, we need to update spottability when we utilize `animateTo`, in addition to when the `indexChanged` handler is run.
We have factored out spottability update code into its own method, and call that from the appropriate methods.
=> ENYO-1880: Add ability to change indices without transition animation.

lib/ContextualPopup/ContextualPopup.less
The shadow pointer tip in contextual popup is found truncated in both dark and light css theme. The issue caused by the improper usage of tip height and width css property.
The height and width css property of contextual popup tip made 0 to get the proper triangle share. The margin css properties of the tip also changed to accommodate the new change.
DCO-1.1-Signed-Off-By: Anish TD anish.td@lge.com
=> ENYO-1160: Shadows Pointer Tip of ContextualPopup is Truncated

lib/Drawers/Drawer.js, lib/Drawers/Drawers.js
In the prior implementation of Drawers, the internal enyo/Drawer would hide its client area thereby informing Spotlight that the currently spotted control was hidden and another control needed to be. With the removal of the internal enyo/Drawer, the spotted control or its ancestors were not hidden so spotlight didn't update.
Add a hook to onDrawerAnimationEnd in moonstone/Drawers to hide the active drawer if it is completely closed.
=> Fixes ENYO-1955

lib/Icon/Icon.js, lib/Icon/IconAccessibilitySupport.js
Screen reader reads Icon unicode content (e.g. &#983040 ) when developer adds accessibilityHint to Icon
In Moonstone Icon, predefined icon(e.g. drawer, check, closex ..) is font-based Icon and set unicode text to content. However, If developer add accessibilityHint to Icon, at first, check whether or not accessibilityLabel or content exists. Thus, If accessibilityLabel does not exists and accessibilityHint is added, screen reader reads unicode content and hint message because Icon has content as unicode text
override updateAccessibilityAttributes function so screen reader can not read unicode content.
=> ENYO-2017 : Remove Icon unicode content from Icon accessibilityHint message

css/moonstone-variables.less, lib/Header/Header.less
…without clipping
Title below is pulled up to account for the taller header-title height.
=> PLAT-1373: Adjusts the line-height for headers to accommodate accented characters

lib/Panels/Panels.js, lib/Panels/Panels.less
When programmatically focusing the Panels handle, the browser would scroll it
to center throwing off the layout. A similar scrolling issue occurred when quickly navigating back through multiple panels.
Setting overflow: hidden, as inherited from .enyo-arranger resolves the first issue. Adding accessibilityPreventScroll to clientWrapper resolved the second.
=> Fixes ENYO-2032

lib/ExpandableListItem/ExpandableListItem.js
Issue:
- ExpandableListItem header is currently set as a control.
- Disabled control is focusable.
Fix:
- Change header kind as moon.Item so it can get spotlight focus.
=> ENYO-1636: Make ExpandableListItem header moon.Item

lib/LightPanel/LightPanel.js
We are currently attempting to spot the current panel if there is no spotlight focus, without taking into account pointer mode and/or whether or not the current item is spottable. Additionally, we want to allow for custom logic to be executed once the deferred client components have actually been created and rendered.
I've cherry-picked the following commit from @KunmyonChoi to resolve the first issue: https://github.com/enyojs/moonstone/commit/568ef3784e50d4eeaa6284edd8702124e4edb5. And for the second issue, we've followed the pattern of `enyo.DataList` and execute the `didClientRender` method if applicable.
=> ENYO-1589: Fix and enhance post transition behavior

source/ExpandablePicker.js, source/MoonScrollStrategy.js
In 5-way mode, when selecting an item in an `ExpandablePicker`, we are explicitly spotting the header, which bubbles the `onRequestScrollIntoView` event if the picker is open, causing an undesired appearance of the vertical scroll thumb.
We have switched the order of the calls in `selectAndClose` such that we update the active state *after* spotting the header. This allows for the spotting of the header to not overlap with the animated close of the drawer. Specifically, the animation of the drawer caused the scroller's `bottomBoundary` to be non-zero, which is a gating condition for triggering `alertThumbs` in `MoonScrollStrategy`.
I also went back through the history of `ExpandablePicker` to make sure we had not specifically changed the order of these calls to fix any specific issues. I …
=> ENYO-2075: Switch order of setting active state and header spotting.

lib/CheckboxItem/CheckboxItemAccessibilitySupport.js, lib/Item/Item.js, lib/Item/ItemAccessibilitySupport.js, lib/SelectableItem/SelectableItem.js, lib/SelectableItem/SelectableItemAccessibilitySupport.js
Screen reader does not read SelectableItem content and status when SelectableItem is focused  
SelectableItem looks like general radioItem, which has text and radio mark. To support accessibility, we have to add aria-related role and attribute. In SelectableItem, role is 'radio' and it needs 'aria-checked' attribute to inform whether or not SelectableItem is checked. In Addtion to, SelectableItem extends moonstone Item, which can have child components like icon or simple control, so we have to add aria-labelledby attribute for reading child content to moonstone Item.
add radio role , aria-checked and aria-labelledby attribute to SelectableItemAccessibilitySupport mixin
=> ENYO-1899 : Add Text to Speech Accessibility support to SelectableItem

lib/Accordion/Accordion.js, lib/Accordion/AccordionAccessibilitySupport.js
Apply accessibility on Accordion
When developer adds accessibilityLabel to Accordion, screen reader does not read accessibilityLabel text.
aria-label is added to Accordion's root dom node when developer adds accessibilityLabel. However, Accordion's child headerWrapper has the spotlight focus when it is focused, so should add accessibilityLabel to this child component. Additionally, Accordion header text is child header component text, so we should set 'aria-labelledby' to this child component's Id and add accessibilityDisabled:true to this child component to prevent reading text when user clicks header component using pointer
Add accessibilityLabel to child headerWrapper component and set aria-labelledby to header component id.
Enyo-DCO-1.1-Signed-off-by: Bongsub Kim …
=> ENYO-1890: Add Text to Speech Accessibility support to Accordion

lib/ExpandableInput/ExpandableInput.js, lib/ExpandableInput/ExpandableInputAccessibilitySupport.js
According to UX guide it should read
<header> + <current value> + <edit box>,
so I added 'aria-label' combining all of them.
https://jira2.lgsvl.com/browse/ENYO-1903
=> ENYO-1903: Add Text to Speech Accessibility support to Expandable Input

lib/SimplePicker/SimplePicker.js, lib/SimplePicker/SimplePickerAccessibilitySupport.js
Blink will support 'aria-valuetext' for spinbutton, so we apply
spinbutton role for SimplePicker.
We don't need to manage children controls accessibilityDisabled
because if it set 'aria-hidden' true on parent, children will be
hidden as well.
https://jira2.lgsvl.com/browse/ENYO-1892
=> ENYO-1892: Add Text to Speech Accessibility support to SimplePicker

lib/ExpandableListItem/ExpandableListItem.js, lib/ExpandableListItem/ExpandableListItemAccessibilitySupport.js
Apply accessibility on ExpandableListItem.
When developer adds accessibilityLabel to ExpandableListItem, screen reader does not read accessibilityLabel text.
aria-label is added to expandableListItem's root dom node when developer adds accessibilityLabel. However, ExpandableListItem's child headerContainer has the spotlight focus when it is focused, so should add accessibilityLabel to this child component. Additionally, ExpandableListItem header text is child header component text, so we should set 'aria-labelledby' to this child component's Id.
Add accessibilityLabel to child headerContainer component and set aria-labelledby to header component id.
=> ENYO-1993: Add Text to Speech Accessibility support to ExpandableListItem

css/moonstone-mixins.less, lib/Button/Button.js, lib/Button/Button.less, lib/Icon/Icon.js, lib/Icon/Icon.less, lib/ToggleSwitch/ToggleSwitch.less
Added a tap-area mixin to universally add tap-area support to controls which need it, by simply adding a single line which includes their current size.
Removed vestigial JS logic and control code to handle adding and removing of tap-areas.
Directly affected controls: Icon, Button, ToggleSwitch
Also updated all other mixins to not output themselves directly as CSS, and instead only the contents will be output when being mixed-into another control's rule-set.
=> ENYO-2118: Added a tap-area mixin

lib/ToggleSwitch/ToggleSwitch.less
Misaligned ToggleSwitch icon on TV
add vertical-align to ToggleSwitch icon
=> Fixes ENYO-1959

lib/IconButton/IconButton.less
Issue:
Button is showing active state while hold and drag to outside of button
Fix:
Use .spotlight with :active to show active state
=> ENYO-2124: IconButton active state remains while hold and drag

lib/Accordion/Accordion.js, lib/DateTimePickerBase/DateTimePickerBase.js, lib/ExpandableInput/ExpandableInput.js, lib/ExpandableIntegerPicker/ExpandableIntegerPicker.js, lib/ExpandableListItem/ExpandableListItem.js, lib/ExpandableListItem/ExpandableListItem.less, lib/ExpandablePicker/ExpandablePicker.js, lib/ExpandablePicker/ExpandablePicker.less
Most (all?) of the kinds extending moonstone/ExpandableListItem are incorrectly reusing CSS classes from moonstone/ExpandablePicker resulting in incorrect styling when moonstone/ExpandablePicker is not included in a build.
Refactor moonstone/ExpandablePicker css into moonstone/ExpandableListItem which the former extends
=> Fixes ENYO-2030

lib/DayPicker/DayPicker.js
We missed updating `moon.DayPicker` to utilize the `Signals` module.
Updated to use the `Signals` module instead of the string kind name.
=> ENYO-1864: Utilize module instead of string kind name.

lib/SimplePicker/SimplePickerAccessibilitySupport.js
This issue occurs because no null check for this.selected on
SimplePickerAccessibilitySupport.
Add null check for this.selected.
https://jira2.lgsvl.com/browse/ENYO-2127
=> ENYO-2127: Accessibility: The TypeError occurs in the calendar

lib/IntegerPicker/IntegerPicker.js, lib/IntegerPicker/IntegerPickerAccessibilitySupport.js
In case using 'aria-live' there is an issue that it reads 'aria-label'
three times.
Blink team suggested using 'spinbutton' role on integer picker, so
applic 'spinbutton' role.
Note that 'spinbutton' role doesn't work on chrome vox.
https://jira2.lgsvl.com/browse/ENYO-1891
=> ENYO-1891: Add Text to Speech Accessibility support to Integer Picker

lib/SimpleIntegerPicker/SimpleIntegerPicker.js, lib/SimpleIntegerPicker/SimpleIntegerPickerAccessibilitySupport.js
SimpleIntegerPicker has unit property, so set unit text to
accessibilityLabel.
=> Fixes ENYO-2142

lib/NewDataList/NewDataList.js
Old guard code didn't account for the case where `event.index` was
zero.
=> ENYO-2158: Fix guard code in `avoidScrollOnDefaultFocus`

lib/ExpandableListItem/ExpandableListItem.js
first item in the client area, and close the list, f the focus moves out
of the drawer and auto-collapse is true.
Enyo-DCO-1.1-Signed-off-by: Rajyavardhan P <rajyavardhan.p@lge.com>
=> ENYO-2131-inconsistent behavior of spotlight on auto collapse

lib/ExpandablePicker/ExpandablePicker.js
By both pushing the control and updating its checked state, the control
was added to the selected array twice. Instead, we'll rely on the
onActivate handler to add it to selected and just update checked.
=> Fixes ENYO-2141

lib/ExpandableListItem/ExpandableListItem.less, lib/Icon/Icon.less
Add CSS rule for ExpandableListItems within moon-neutral containers
=> Fixes ENYO-2155

lib/ScrollStrategy/ScrollStrategy.js
scroll thumb.
Issue:
- The moon.Scroller doesn't have a way to detect content changes.
- So, we need to bubble up onRequestSetupBonds to update scroll boundary
and thumb state.
- The problem is even if moon.Scroller (moon.ScrollStrategy) update it's
scroll bounds and enable scroll thumb area. All the items inside
doesn't get any notice from scroller when scroll thumb area is
reserved by strategy (push padding-right).
Fix:
- It need to call resize on scroller when scroll thumb state is changed,
because the scroll content area and item width is actually changed.
=> ENYO-2168: Marquee doesn't recalculate distance when scroller show/hide

lib/InputDecorator/InputDecoratorAccessibilitySupport.js
Apply accessibility on InputDecorator.
Read placeholder of current input using readAlert api
when spotlight focused. The reason why we use readAlert is
if we set focus on input it becomes to editable mode,
but we just want to just move spotlight focus.
https://jira2.lgsvl.com/browse/ENYO-1910
=> ENYO-1910: Add Text to Speech Accessibility support to Input

css/moonstone-mixins.less, css/moonstone-variables-dark.less, css/moonstone-variables-light.less, lib/Header/Header.less, lib/Input/Input.less, lib/VideoPlayer/VideoPlayer.less
When we merged the changes from https://github.com/enyojs/moonstone/pull/1945, we missed the fact that there were mixed vendor-specific selectors for `InputHeader`'s styling, which will cause the browser (at least WebKit) to stop parsing the rule once an unrecognized selector is hit. This resulted in several previously-applied styles disappearing from `InputHeader`.
This may have gone the way of over-generalization as this is primarily useful in the cases where we have vendor-specific selectors that need the same rules applied while wanting to keep things DRY, but I've added a mixin function that accepts a rule and an array of selectors, and in turn applies the rules to each of these selectors. This assumes that you are calling the mixin function (`explode-rule`) inside a selector (which …
=> ENYO-1313: Separate out vendor-specific pseudo-selector rules.

lib/VideoPlayer/VideoPlayer.less
Also updated IE's fullscreen pseudo-selector.
More details: https://developer.mozilla.org/en-US/docs/Web/CSS/:fullscreen
=> ENYO-2062: Corrected fullscreen pseudo selector to match W3 spec

lib/PagingControl/PagingControl.less, lib/ScrollControls/ScrollControls.less, lib/ScrollControls/package.json, lib/Scroller/Scroller.less
* Make ScrollControls explicitly depend on styles from Scroller
and PagingControl (as a temporary measure). Until now, this
dependency has been implicit, which causes ScrollControls to be
laid out improperly when used in an app that doesn't also include
Scroller and PagingControl.
* Apply a positive z-index to ScrollControls' scroll columns, so
that they reliably appear above scroller contents.
=> ENYO-2220, ENYO-2221: ScrollControls styling

lib/TimePicker/TimePicker.js
TimePicker dstOffset is not working properly on dreadlocks.
Dreadlocks support round up already, so we do not need one hour round up again.
removed one hour round up which is webOS specific.
Enyo-DCO-1.1-Signed-Off-By: Suhyung Lee (suhyung2.lee@lge.com)
=> ENYO-2232 : TimePicker dstOffset is not working properly on TV.

lib/LightPanel/LightPanel.js
The default value for `moonstone/Header`'s `marqueeOnRenderDelay` of `10000` was being used.
This value has been adjusted to a more-reasonable `1000` so that it begins shortly after we transition to / show a panel.
=> ENYO-2235: Use a more reasonable value for marqueeOnRenderDelay.

lib/NewDataList/NewDataList.js, lib/Scroller/Scroller.less
Programmatic `focus()`-ing controls causes the browser to scroll the control into view using `scrollTop` and `scrollLeft` on the nearest scrolling context ancestor that would bring it into view
Remove `overflow` from intermediate controls within scroller so that scrolling can be suppressed on the scroller.
=> Fixes ENYO-2223

lib/Header/Header.js, lib/Header/Header.less
… and rearranged the rules for ideal precedence.
Also (finally) added a `.moon-large-header` class to remove many unnecessary rules that just get overridden.
=> ENYO-2199: Restored the custom JP header sizing

lib/Marquee/Marquee.js
Issue.
When the marquee is hidden, the animation jobs are not cancelled. 
Fix.
When the marquee is hidden, remove focus, and stop the marquee.
=> ENYO-2229: Marquee rolls unexpectedly when display changes

lib/NewDataList/NewDataList.js, lib/Scrollable/Scrollable.js
* When doing continuous / accelerated 5-way scrolling, scroll an
element at a time instead of a page at a time. This produces
smoother scrolling.
* When 5-way focusing an element inside a scroller and focus was
previously outside the scroller or on one of the scroll controls,
minimize the distance scrolled to bring the element into view. This
produces a less jarring effect.
These changes necessitated some refactoring of existing logic for
filtering onSpotlightFocus events. The new factoring is explained
with inline comments.
The changes also depend on a new feature in Spotlight. The
onSpotlightFocus and onSpotlightFocused events now indicate
which element was previously focused, which enables handlers to
discriminate on that basis as necessary.
Bonus commits (not related to task) add some …
=> ENYO-2224: Improve 5-way scrolling in Scrollable / NewDataList

lib/LightPanels/LightPanel.js
I created a bad merge for https://github.com/enyojs/moonstone/pull/2277 by helping git merge the change from https://github.com/enyojs/moonstone/pull/2374 into the old `LightPanel` control that was eventually deprecated / had its contents gutted.
Re-adding the fix to the new `LightPanel` control location.
=> ENYO-2235: Re-add the more-reasonable marqueeOnRenderDelay value.

source/Marquee.js
Issue.
When marquee showing is changed, it does not cause a reflow event.
Fix.
If the marquee is showing then it will recalculate distance. 
=> ENYO-2160: Marquee showingChanged, distance does not recalc

lib/ProgressBar/ProgressBar.less
Slider popup has vertical noise line.
increase left/right part margin of progress-bar-popup to cover vertical blank line
Signed-off-by: Sungbae Cho sb.cho@lge.com
=> ENYO-2231: Slider popup in Contextual Popup has vertical blank

lib/Marquee/Marquee.js
- When index changed, lightPanels does teardownRender not destroy on
popOnBack/popOnForward.
- When lightPanels teardownRender, title doesn't stop but stay its
position.
- We stop marquee flow on any active marquee tardownRender.
=> ENYO-2244: Stop active marquee on teardownRender

lib/ListActions/ListActions.js
ListAction checks if actions are arranged vertically or horizontally by comparing total width. However it takes all the components even if their visibility is set to false so it returns incorrect result. Also it doesn't care about resolution independence
Calculate total width by taking only actions whose visibility is set to true and use ri.scale to get proper result based on resolution.
Enyo-DCO-1.1-Signed-Off-By: Hunkyo Jung (hunkyo.jung@lge.com)
=> ENYO-2218: ListActions are stacked vertically, not horizontally

source/ExpandablePicker.js
The scroll bounds for `moon.ExpandablePicker` when the drawer is expanded, are different than when the drawer is about to contract. This is due to how we are showing and hiding the `currentText` element. Before the drawer expands, this element is hidden and does not affect the scroll bounds calculations. But when the drawer is about to contract, the `currentText` element is shown first, causing the scroll height to be greater than the client height, which results in the undesired scroll arrows appearing.
This might be incurring some technical debt, but it seems reasonable to use `asyncMethod` to delay the showing/hiding of the `currentText` element so that it does not impact the scroller calculations, and it seemed to be less obtuse (and intrusive) of a fix than the alternatives. I'm also …
=> ENYO-2110: Ensure that we avoid using the currentText element when computing scroll bounds when drawer is opened/closed.

lib/LightPanels/LightPanel.js
We are subkinding `enyo/LightPanel` for our implementation of `moonstone/LightPanel`, and should execute the super methods for our lifecycle methods.
We execute the super methods for `preTransition` and `postTransition`.
=> ENYO-1981: Call inherited methods of the parent kind.

lib/Slider/Slider.js, lib/Slider/SliderAccessibilitySupport.js
I tried to apply aria attributes on valueChanged, but there are some
issues that if value is changed before animator complete TV reads
the value multiple times.
Set aria-valuenow and aria-valuetext in animatorComplete.
Initialize aria attributes on rendered to get popupContent.
When it initialized we set aria-hidden true to avoid first reading
that if aria-valuenow is set screen reader reads the value, and then
set it false when it spotFocused.
https://jira2.lgsvl.com/browse/ENYO-1895
=> ENYO-1895: Add Text to Speech Accessibility support to Slider

lib/DatePicker/DatePicker.js, lib/DatePicker/DatePickerAccessibilitySupport.js, lib/DateTimePickerBase/DateTimePickerBase.js, lib/DateTimePickerBase/DateTimePickerBaseAccessibilitySupport.js
Apply accessibility on DatePicker.
Basically DatePicker is combined by IntegerPickers, and we already
applied accessibility on IntergerPicker.
According to UX guide, DatePicker should be read <value> +  <day>,
<month> or <year>. I added each text 'day', 'month', 'year' to
'accessibilityLabel', scrren reader will read 'aria-valuenow' +
'aria-label.
https://jira2.lgsvl.com/browse/ENYO-1904
ENYO-1904: Add Text to Speech Accessibility support to Date Picker
change the label for day, month and year to dayText, monthText and
yearText.
https://jira2.lgsvl.com/browse/ENYO-1904
ENYO-1904: remove unused $L
remove unused $L …
=> ENYO-1904: Add Text to Speech Accessibility support to Date Picker

lib/TimePicker/HourMinutePickerBaseAccessibilitySupport.js, lib/TimePicker/MeridiemPickerAccessibilitySupport.js, lib/TimePicker/TimePicker.js, lib/TimePicker/TimePickerAccessibilitySupport.js
apply accessiblity on TimePicker
- add accessibilityLabel for hourText, minuteText and meridiemText.
- add MeridiemPicker mixin to support meridiems text.
- add HourMinutePickerBase mixin to support formatted hour.
https://jira2.lgsvl.com/browse/ENYO-1991
=> ENYO-1991: Add Text to Speech Accessibility support to TimePicker

lib/LightPanels/LightPanel.js, lib/LightPanels/LightPanels.js
When subkinding `moonstone/LightPanels/LightPanel`, there are cases where the state of the control needs to be examined. This requires retrieving the States hash from `enyo/LightPanels/LightPanel`.
To improve developer ergonomics, we expose the States hash on `moonstone/LightPanels/LightPanel`. 
I'm curious if we have an established pattern for "passing-through" a module property to a subkind, or if there is a better way of doing this.
=> ENYO-2254: Expose States.

lib/ClampedText/ClampedText.less
=> ENYO-2242 Right side of ExpandableText is cut off

lib/Accordion/Accordion.js, lib/Button/Button.js, lib/CheckboxItem/CheckboxItem.js, lib/ExpandableInput/ExpandableInput.js, lib/ExpandableListItem/ExpandableListItem.js, lib/ExpandablePicker/ExpandablePicker.js, lib/IntegerPicker/IntegerPicker.js
Blink is changed to ignore the child node if it has aria-hidden even though
parent has aria-labelledby.
We need to remove accessibilityDisabled in child node if it is dispensable.
https://jira2.lgsvl.com/browse/ENYO-2255
=> ENYO-2255: remove accessibilityDisabled in child node.

lib/ScrollStrategy/ScrollStrategy.js
When one set of scrollbars is visible (usually the vertical), there are certain circumstances where the `setupBounds` method of `moonstone/ScrollStrategy` can be executed when the scroller is not visible. This results in an infinite loop by the way of the `resize` method.
More specifically, during the first loop, the vertical scrollbars are disabled, which results in the `v-scroll-enabled` class being removed from both the vertical and horizontal scroll columns (this is always done in lock-step). After this occurs, we compute whether or not the horizontal scrollbars should be visible. We had previously computed our scroll bounds with the `v-scroll-enabled` class already enabled, and thus there is a horizontal offset that results in determining that we need horizontal scrollbars, which …
=> ENYO-2312: Prevent calling resize, while already resizing.

css/moonstone-variables.less, lib/Header/Header.less
=> PLAT-1948: Reduced the header font size to allow for deeper glyphs (like j, y, g)

lib/Slider/Slider.js
When enableJumpIncrement is set to true, slider has left and right buttons to move towards left or right based on jumpIncrementAmount. However if we use MRCU, the status of the two buttons are not updated.
While dragging the knob, we check the status of jumpIncrement buttons based on the current value.
Enyo-DCO-1.1-Signed-Off-By: Hunkyo Jung (hunkyo.jung@lge.com)
=> ENYO-2315: JumpIncrement button status in slider is not updated

lib/SimplePicker/SimplePicker.less
Issue.
Cause: Appears that .moon-marquee was overriding .moon-simple-picker-client>*, changing from 100% to auto
Fixes the following reported issues from ENYO-2309:
TV Guide SimplePicker: Date is displayed without space
Settings SimplePicker: 2 items displayed at the same time
Enyo-DCO-1.1-Signed-off-by: Derek Anderson derek.anderson@lge.com
=> ENYO-2328 moon-marquee was overriding .moon-simple-picker-client>*

lib/ExpandableListItem/ExpandableListItem.js, lib/ExpandableListItem/ExpandableListItemHeader.js
Current value of expandable picker does not get the allowHtml property passed to it, so values with HTML do not display properly. Test ExpandablePickerSample and select the 'Symbols' line.
In ExpandableListItemHeader, pass `allowHtml` to the text item.
Also cleaned up jshint warnings.
=> ENYO-2363 allowHtml with Expandable header

lib/ExpandableInput/ExpandableInput.js, lib/ExpandableListItem/ExpandableListItem.js
The logic in `currentValueShowing` used `currentValueText` but only declared `value` in its computed list. Since ExpandablePicker overrides the computed path for `currentValueText` to use `selected` and `selectedIndex`, the value of `currentValueShowing` wasn't updated correctly.
Update the computed path to use `currentValueText` instead of `value`
=> Fixes ENYO-2362

lib/Popup/Popup.less
With merged PR, popup close button does not get spotlight's background color. So, I made reverted PR.
Enyo-DCO-1.1-Signed-off-by: Suhyung Lee suhyung2.lee@lge.com
=> ENYO-2334: Popup close button misaligned and with background color - reverted

lib/History/History.js
correctly forward enableBackHistoryAPI property
=> Fixes ENYO-2368

css/moonstone-mixins.less, css/moonstone-variables-dark.less, css/moonstone-variables-light.less, lib/Button/Button.less, lib/Icon/Icon.less, lib/IconButton/IconButton.less
Issue
------
It is not easy to distinguish disabled and enabled Icon button with translucent status
Cause
--------
Background color and opacity are same in both
Fix
----
Button and IconButton are now more translucent to allow for easier differentiation, as well as colors between them being synced-up.
This change includes:
* Several LESS variable name changes to be more consistent with other names
* Several deletions of abandoned deprecated LESS variables
* A correction to button's disabled attribute reference (it doesn't rely on a class)
* Addition and implementation of new `.vendor-opacity` mixin
* Simplification of the translucent/transparent CSS rules for Button, IconButton
Enyo-DCO-1.1-Signed-off-by: Blake Stephens …
=> Enyo-2314 Change disabled Icon color and opacity to make differences

lib/LightPanels/LightPanel.js
Applying same fix with ENYO-2130 on LightPanel.
=> ENYO-2347: spotlightPlaceholder isn't disabled when a panel add component after creation time.

src/VideoPlayer/VideoPlayer.js
This is related to "https://github.com/enyojs/enyo/pull/1194"
added flag, "isNeedPlay", in enyo.Video,  to make node play after setPlaybackRate.
With above modification, we need to change moon.VideoFeedback also.
Flow of moon.VideoFeedback is like below.
1. this.setPlaybackRate(this.selectPlaybackRate(this._speedIndex));
"setPlaybackRate" -> "doSlowforward" in "ratechange" function in enyo.Video
-> through moon.VideoPlayer, sendFeedback("Slowforward") to moon.VideoFeedback
So, feedText in moon.VideFeedback displays Slowforward info now.
2. node.play();
"doPlay" in enyo.Video
-> through moon.VideoPlayer, sendFeedback("Play") to moon.VideoFeedback
So, feedText in moon.VideFeedback displays Play info now.
The feedText should display Slowforward info.
I added below code in moon.VideoPlayer. …
=> ENYO-1725: enyo.Video: setPlaybackRate should be called ahead of play in a certain case

src/ContextualPopup/ContextualPopup.js, src/Popup/Popup.js
Requirement from HE UX
Issue
-------
When spotlightModal is true, we should block to close popup although back key is pressed.
Cause
--------
Currently popup will be closed when back key is pressed
Fix
----
Add guard code to prevent closing popup
=> Enyo 2391 Prevent to close popup with back key when spotlightModal is true.

src/ContextualPopupDecorator/ContextualPopupDecorator.js
Issue
-------
Activate method could not close Popup
Cause
--------
This is a regression issue of modular work.
Added line was missing during modulization.
Fix
----
Restore missing line
=> Enyo-2034 Close popup using activated method

src/DateTimePickerBase/DateTimePickerBase.js
When the DateTime picker is opened and then changed the locale, the picker collapsed and look like it is closed. But the arrow still points upwards (^) and the property remains as opened.
onLocaleChanged the picker is destroying and recreating the client control  but the open property is not resetting to false.
In refresh() function DateTimePickerBase, the open property resettled to false.
DCO-1.1-Signed-Off-By: Anish TD anish.td@lge.com
=> ENYO-1852: Time/DatePicker closed status not properly updated with locale change

src/LightPanels/LightPanel.js, src/LightPanels/LightPanel.less, src/LightPanels/LightPanels.less, src/LightPanels/package.json
With the fix for ENYO-2384 to transition a single panel container instead of individual panels, the transition scrim applied to each panel could also be moved to the panel container. Also, I noticed the header marquee was running during transition.
The transition scrim is now being applied to the panel container. We also utilize the composite class for the client element when populated. And lastly, the marqueeing of the header is now explicitly controlled via the transition lifecycle methods. This is not a perfect solution as auto-marqueeing kinds in the view could potentially still marquee during transition, but these seemed much more rare, and this was a decent compromise for a known auto-marqueeing kind, rather than waterfall an event to all of the panel elements. …
=> ENYO-2421: Move transition scrim to panels container.

src/ExpandablePicker/ExpandablePicker.js
Issue:
CurrentValueText is not updated when user change content of selected item on ExpandablePicker.
Fix:
Add a binding from selected content to currentValueText to trigger
compute.
=> ENYO-2437: Recompute when selected item content changes on ExpandablePicker

css/moonstone-dark.css, css/moonstone-light.css, css/moonstone-text.less
Issue:
webOS Webkit, is misreading font widths without font-kerning applied to them.
Fix:
Add the font-kerning mixin
Enyo-DCO-1.1-Signed-off-by: Derek Anderson derek.anderson@lge.com
=> Enyo-2003 Marquee is not starting for "Revoke all pairing authorizations" pop-up.

src/ExpandableText/ExpandableText.js
Initial add accessibility feature to ExpandableText
WebOS TV should read all content of ExpandableText when more or less button is focused though content is collapsed.
ExpandableText has client and button component. The client component has content and button is more or less button. Screen reader should not read more or less button content when this button is focused. Instead, it should read all content of client component, To implement this requirement, we add aria-labelledby attribute, which has client component id to more or less button. 
=> ENYO-2021: Add Text to Speech Accessibility support to ExpandableText

src/Panel/Panel.js
Give Panel a default role of region and toggle it to alert when
activated so it is read immediately. May need to revist if/when browser
will read region consistently when a contained control is focused.
Issue: ENYO-1994
=> toggle role on Panel when activated

src/Header/Header.less
Issue:
- When marquee text is used with 100% width inside of headerComponents,
it is not have ellipsis when text is large enough.
- Marquee Text is having two times larger width than panel.
Fix:
- Add 100% max-width on moon-header-client. So that inner controls can
not have larger width than panel.
=> ENYO-2446: Adding max-width 100% on header client

src/LightPanels/LightPanel.js
We had originally set `marqueeOnRender:false` for `LightPanels` in order to prevent any unnecessary marqueeing i.e. the time between the panel rendering and `preTransition` being called. This would really only be an issue if we set a very small `marqueeOnRenderDelay` value. But semantically, this is not quite accurate and by extension not compatible with https://github.com/enyojs/moonstone/pull/2507, because we *do* want the header's title to marquee upon "render", just that our definition of "render" would be after the transition is complete, and so we control this programmatically via the panel lifecycle methods.
We have removed the `marqueeOnRender:false` setting of the header in `LightPanels` - our value for `marqueeOnRenderDelay` is sufficiently large enough that this should not be a …
=> ENYO-2463: Correct semantics of marqueeOnRender for header.

src/ListActions/ListActions.js
Initial add accessibility feature to ListActions
1) Screen reader should read ListAction IconButton's tooltip text when it is focused.
2) Screen reader should read ListAction Item content and state when ListAction's item is focused.
3) Screen reader should read close string when ListActions close button is focused.
Only No.3 requirement is applied because the others are already applied in each component.
To read 'close' when close button is focused, we add accessibilityLabel to IconButton. 
=> ENYO-1908: Add accessibilityLabel for close iconButton of ListAction

src/InputDecorator/InputDecorator.js
If Input type is 'dismissOnEnter:true', it does not read the value after 'Enter' button is clicked.
In input focus state, spotted is true, and If user press enter, TV does not read again own inputDecorator's label because spotted is not changed.
set spotted to true when input is focused in spotlightSelectHander, and if input type is dismissOnEnter and press enter, set spotted to true in new added keyupHandler. 
=> ENYO-2238: Fix not reading when press enter dismissOnEnter input

src/Drawers/Drawers.js
Initial add accessibility feature to Drawers.
Screen reader should read 'open drawer' or 'close drawer' when Drawer is focused.
Screen reader should read 'open drawer' or 'close drawer' when activator of drawers is focused according to drawer open or close state. 
Whenever drawer is opened or closed, updateActivator is called and Drawers could know whether or not drawer is open using isDrawerOpen function 
Thus, I added accessibility function to updateActivator function. 
=> ENYO-1907: Add Text to Speech Accessibility support to Drawer

src/ContextualPopup/ContextualPopup.js, src/Panels/Panels.js
There are a couple controls that are not initially declared as
spottable but may become so at runtime. Setting tabIndex on them so
they are focusable for accessibility.
=> Fixes ENYO-2430

src/ExpandableListItem/ExpandableListItem.js, src/GridListImageItem/GridListImageItem.js, src/ImageItem/ImageItem.js, src/LabeledTextItem/LabeledTextItem.js
On expandable control the header control can get spotlight focus,
we set the aria-label on the header if it is needed.
The cases we should consider are
- accessibilityLabel set
: read only <accessibilityLabel>
- accessibilityHint set
: read <content> + <current value> + <accessibilityHint>
- accessibilityLabel and accessibilityHint set
: <accessibilityLabel> + <accessibilityHint>
apply similarly on ImageItem and LabeledTextItem.
https://jira2.lgsvl.com/browse/ENYO-2152
=> ENYO-2152: screen reader does not read accessibilityHint of component that has aria-labelledby

src/InputDecorator/InputDecorator.js
Remove aria-live from InputDecorator when not spotted. This prevents the browser from reading the contents instead of the aria-label when spotting a different control.
=> Fixes ENYO-2431

src/LightPanels/LightPanels.js
In the case where we have a static components block with spottable components, inactive panels are still spottable and cause Spotlight focus to effectively be lost.
We now explicitly set the `spotlightDisabled` value accordingly. Technically, Spotlight checks the `showing` property to cover this case, but we had specifically wanted to avoid setting this property and waterfalling the `showingChanged` event, each time. I am open to revisiting this and weighing the pros and cons between the two approaches.
=> ENYO-2492: Prevent spotting of inactive panels.

src/DataList/DataList.js
Issue:
DataList is give focus on specific item when initialFocusIndex is set.
But, when that item is disabled, Spotlight fails give focus.
Fix:
Check spottability on item before give focus, then give focus on list
instead when that item is not focusable. This workaround will give focus
to the first focusable item on list.
Enyo-DCO-1.1-Signed-off-by: Kunmyon Choi <kunmyon.choi@lge.com>
=> ENYO-2501: Lost focus when set initialFocusIndex on disabled item in DataList

src/Calendar/Calendar.js, src/Clock/Clock.js, src/DateTimePickerBase/DateTimePickerBase.js
Inconsistent and incorrect application of internal locale api's caused bad results when attempting to update to current locale.
Update documentation, correctly use internal api's, and deprecate the Calendar widget that needs to be re-written to correctly make use of the locales.
Tied to these other PR's:
https://github.com/enyojs/enyo-strawman/pull/137 
https://github.com/enyojs/enyo-ilib/pull/146
Enyo-DCO-1.1-Signed-Off-By: Cole Davis (cole.davis@lge.com)
=> Fix for: ENYO-1859

src/LightPanels/LightPanel.js
As a result of the changes in https://github.com/enyojs/enyo/pull/1279, we corrected some of the panel transition state semantics, as well. These changes should be reflected by any consumers of these states.
We have now updated the states we are checking in `moonstone/LightPanel`.
=> ENYO-2491: Update to reflect the corrected semantics of our panel states.

src/Calendar/Calendar.js, src/Clock/Clock.js, src/ContextualPopup/ContextualPopup.js, src/DateTimePickerBase/DateTimePickerBase.js, src/Dialog/Dialog.js, src/ExpandableListItem/ExpandableListItem.js, src/GridListImageItem/GridListImageItem.js, src/ImageItem/ImageItem.js, src/InputDecorator/InputDecorator.js, src/LabeledTextItem/LabeledTextItem.js, src/Panels/Panels.js, src/ScrollStrategy/ScrollStrategy.js, src/Slider/Slider.js
For subkinds of DateTimePickerBase, the value of currentValueText is
formatted for the locale. The local locale member is deprecated by
ENYO-1859 so we must manually notify observers of currentValueText to
refetch its value when the locale changes.
=> Fixes ENYO-2516

css/moonstone-mixins.less, css/moonstone-text.less, src/ContextualPopupButton/ContextualPopupButton.less
The Moonstone Icon font (as of the current version) has no kerning information, which means if kerning rules are enabled, none of its glyphs render. We must reset anything that uses the font to *not* use kerning "normal".
=> ENYO-2494: Contextual Popup Buttons once again have their chevron arrows

src/TimePicker/TimePicker.js
`this.pickers` represents a set of picker like hour and minute.
In setupPicker(), we compose it.
Then when timePicker open, it will reflow each picker using `this.pickers`
=> Enyo-2522 Reflow each picker when timePicker is opening

src/Slider/Slider.js
Issue
It can not set slider custom value if no popup
For TV Settings app, there are many cases it needs to set
custom value without popup.
Cause
If popup is false in Slider, app developer can not set custom value
at the slider.
In case popup is true, app developer can set custom value
through popupContent.
Fix
Add accessibilityValueText property to set custom value for slider
https://jira2.lgsvl.com/browse/ENYO-2564
=> ENYO-2564: it can not set slider custom value if no popup

src/Icon/Icon.less
This resolves an issue where the Moonstone Icons font is rendered invisible due to the font itself not having built-in (or correct) kerning information. (And is therefore unable to render anything visibly to the screen.)
=> ENYO-2559: Explicitly set Icon (and IconButton) to not allow kerning.

src/LabeledTextItem/LabeledTextItem.js
When text in LabeledTextItem is updated with LTR, RTL or a mix of both, base direction is not properly updated.
If binding for the text is triggered, we check the directionality of the given text.
=> ENYO-2539: LabeledTextItem: Text direction is not updated for right-to-left text

src/ContextualPopup/ContextualPopup.js
In the RTL case, Contextual Popup is shown in an abnormal position for the first time only.
The bug occurred when the reserve-close class was added without a reflow/resize. So, add a reflow to the end of ContextualPopup::configCloseButton()
Enyo-DCO-1.1-Signed-off-by: Krishna Rangarajan <krishna.rangarajan@lge.com>
=> ENYO-2274: Contextual Popup position bug

src/Tooltip/Tooltip.js
The spacing between the activator and the tooltip were the same amount of pixels, regardless of resolution.
We scale the default padding and margin via `ri.scale`.
=> ENYO-2581: Scale default padding and margin.

src/SimplePicker/SimplePicker.js
When child components are created in the creation time, nav buttons are shown as disabled.
`this.generate` is always false in `create` function, which would skip executing `showHideNavButton` function to update the disablement status. 
Change the condition for `showHideNavButton` in `addControl` function so that nav buttons' disablements are updated prior to being rendered.
=> ENYO-2448: Allow nav buttons to update disablement in creation time

src/IntegerPicker/IntegerPicker.js
Sometimes, scrolls were being dropped so that the internal and
displayed values were out of sync. Wrapping both the 'setup'
scrollToIndex and the animated scrollToIndex in rAF should (and appears
to) ensure that both complete in separate frames. We also cancel any
existing rAF to ensure that a prior one doesn't complete later thereby
effectively cancelling the scroll.
=> Fixes ENYO-2582

src/ExpandablePicker/ExpandablePicker.js
When ExpandablePicker is created, selectedIndexChanged() is called for initialization. If nothing is selected, getSelectedIndex() returns -1 which is default value. And then if the picker doesn't support multipleSelection it calls setSelected with selected control. However index is set to -1 which is out of bounds and undefined is returned.
If index is set to invalid value like -1, `selected` would be set to `null`.
Enyo-DCO-1.1-Signed-off-by: Hunkyo Jung (hunkyo.jung@lge.com)
=> ENYO-2406: ExpandablePicker: getSelected() returns undefined, not null

src/ContextualPopup/ContextualPopup.js
a reflow() call added at the end of ContextualPopup::configCloseButton() caused ContextualPopup direction not to work
The ContextualPopup::requestShow() method called show(), then configCloseButton(). The call to show() triggered a call to showingChanged(), which called alterDirection(), which positioned the contextualPopup according to the "direction" property. When configCloseButton() called reflow() after this moon.ContextualPopup positioning code had been called, it resulted in a call to enyo.Popup::reflow(), which called enyo.Popup::updatePosition(), which repositioned the popup without reference to the moon.ContextualPopup "direction" property.
There seem to be a few possible fixes for this. One would be to have moon.ContextualPopup() override the enyo.Popup::updatePosition() …
=> ContextualPopup: Direction does not work after pre.17

src/IntegerPicker/IntegerPicker.js, src/SimpleIntegerPicker/SimpleIntegerPicker.js
Issue
When spotlight is focused on IntegerPicker with min value,
it reads 'value' + 'change a value with up down button',
but in this case we can not use 'down' button because the value is minimum
and down icon is disabled.
It should be read 'value' + 'change a value with up button'
Cause
added same hint without considering wrap property
Fix
add each proper hint when wrap is false.
- when value is the same as min, use only 'up'
- when value is the same as max, use only 'down'
- else, use both 'up' and 'down'
change similarly on SimpleIntegerPicker
https://jira2.lgsvl.com/browse/ENYO-2626
=> ENYO-2626: Hint is wrong in IntegerPicker

src/ExpandableListItem/ExpandableListItem.js
When we close the drawer in an `ExpandableListItem`, we attempt to spot the header if there is nothing currently spotted. Spotting when in pointer mode has no effect on setting the currently spotted item, but it does call `unspot` and updates the `_oLastControl` reference. In the specific scenario encountered, there is a 600ms default delay in `ExpandablePicker` when an item is selected, before the drawer collapses, potentially causing the spotting of the header to occur after something else has been spotted in response to the item being selected. The `_oLastControl` reference is used for firing container events when there is no currently spotted item, and thus if a container control such as `Popup` is shown when an item is selected, the container events will not fire for the `Popup` as …
=> ENYO-2645: Prevent spotting of header when in pointer mode.

src/Spinner/Spinner.less
Due to low-quality anti-aliasing settings, the spinner had an occasional extra pixel where it visually probably shouldn't. This change subtracts 1px from the size of the spinner to alter the Blink compositor and trick it into rendering a higher-quality edge for each ball, eliminating the blip. 🙅
=> ENYO-2651: Deburred the Spinner Balls

src/Header/Header.js
Title and titleBelow are always {allowHtml:true} in small header even header's allowHtml property is true
Based on header's allowHtml property, escape title and titleBelow string before set title of small header.
Enyo-DCO-1.1-Signed-off-by: Sungbae Cho sb.ch@lge.com
=> ENYO-2666: upadate small header's title to apply allowhtml properly

css/moonstone-variables.less
=> ENYO-2628: Reduce the non-latin Header font-size to prevent layout issues

src/Slider/Slider.js
On repeated key events, an animation can be started before the onEnd
fires. The result can be an incorrect value set because the value on
the animator is mid-animation and not snapped to the increment value.
To avoid this, we'll skip handling the onEnd event when an animation is
in progress.
=> Fixes ENYO-2638

src/fonts.js
=> DRD4TV-3571: Updated Japanese to use all of the available glyphs in the JP font

src/fonts.js
We want the entire font loaded here.
=> DRD4TV-3571: Removed the unicode-range because it's not necessary.

src/Scrollable/Scrollable.js
When we 5-way scroll to an item near the boundary of a scrollable
region, we often (always?) want to scroll all the way to the
boundary.
We've added an option (boundarySnapThreshold) to enyo/ScrollMath,
and we'll use it in moonstone/Scrollable to scroll all the way to
a boundary if our target is within 100 pixels of the boundary.
Both the ScrollMath feature and the way we're using it here should
be considered experimental for the time being and subject to
change.
This change was precipitated by an issue filed against NewDataList,
in which scroll controls weren't being disabled after 5-way
scrolling to the last list item, since the scroll position was a
few pixels shy of the boundary.
=> ENYO-2644: Scrollable: Snap to boundaries

src/Scrollable/Scrollable.js
Oops... `scrollIntoViewOptions` were being specified as an object
literal in the Scrollable mixin definition, which meant they were
inadvertently being shared by all instances. We'll initialize them
in the `create()` method instead.
=> ENYO-2643: Each Scrollable needs its own options!

src/Scroller/Scroller.js
scroller.
Issue:
If controls at the top or bottom (left or right also) are disabled
inside of scroller, there
is no way to show them by 5way key.
Fix:
We force scroll to top or bottom (left or right also) on focus leave
based on last 5way event.
Enyo-1.1-DCO-Signed-off-by: Kunmyon Choi <kunmyon.choi@lge.com>
=> ENYO-2277: Scroll to top/bottom/left/right when focus leave from

src/Overlay/Overlay.js
We need to apply checkbox role on SelectionOverlaySupport.
Set the checkbox role and aria-cheched attributes in
SelectionOverlaySupport.
https://jira2.lgsvl.com/browse/ENYO-1997
Enyo-DCO-1.1-Signed-off-by: Jaewon Jang jaewon98.jang@lgepartner.com
=> ENYO-1997: Add Text to Speech Accessibility support to Overlay

src/Panels/Panels.js
Screen reader reads the title of the panel has 'showing: false'
The active panel has 'alert' role when panel is initially loaded. However, alwaysviewing pattern panel is not shown when TV application is loaded. When user taps the right handle, panel is shown. At that time, 
panels also is shown. 
Add 'showing' property to ariaObservers for observing if panels is showing or hiding.
In addition, add alert role when panels is showing.
=> ENYO-2482 :[Accessibility] Fix reading title when panels is not showing

src/ProgressBar/ProgressBar.js, src/ProgressBar/ProgressBar.less, src/Slider/Slider.js
All tooltips used on ProgressBar and Slider look the same. Choosing a side in vertical progress bar is still an option, since the tooltip orientation shouldn't automatically change when progress is more than 50%.
=> PLAT-10341: Removed customized vertical ProgressBar tooltip

src/LightPanels/LightPanel.js
When going to previous or re-entering to a existing panel, spotlight should remain in the previous spot. In many cases, apps define their `clientComponents` inside a Scroller which has a spotlight container. But in other cases, it won't preserve the last focused item.
Add `spotlight: 'container'` to `client` component
=> ENYO-2717: Add spotlight container to 'client' in LightPanel

src/Slider/Slider.js
When holding enter on the jump increment buttons of Slider, spotlight
would jump to the other button when the first was disabled. The key
events continued to fire since [Enter] had not been released so the
value would start changing in the other direction.
To resolve, note the sender of the keydown event and ignore future
events from other senders until the keyup fires and resets the value.
=> Fixes ENYO-2707

src/ScrollStrategy/ScrollStrategy.js, src/Scroller/Scroller.js
The primary way to scroll in Moonstone when in 5-way mode is to
move focus from one item to another and allow the scroller to
continually scroll the focused item into view as you go.
This means that if the elements closest to a scroller boundary
happen to be unfocusable (either because they're disabled or
because they don't support focus at all), you sometimes can't
scroll all the way to the edge of the scroller.
In this change, we add logic to detect when the just-focused
element is the last focusable element in the direction we're
moving. If it is the last focusable element, then we go ahead and
scroll all the way to the scroller boundary, provided that the
element will still be in view.
A partial solution to the same problem previously went in for
ENYO-2277, but that solution waited …
=> ENYO-2710: "Scroll to boundary" support for Moonstone scroller

src/Slider/Slider.js
When quickly changing the value of a slider, the final one/few change
events can be suppressed by throttleJob resulting in the last onChange
event received by the UI being out of sync with the true value of the
Slider.
To resolve, start a job in the throttleJob callback with the same
duration that fires a final onChange if the value has changed since the
last time onChange was fired.
=> Fixes ENYO-2758

src/DataList/DataList.js
We have recently started getting more aggressive about view
virtualization for performance reasons. One tactic in this area
involves tearing down the DOM representation of a Control and then
restoring it later as needed ("view caching").
In the case where the view being cached / restored contains a
DataList, the state of the view was not being preserved as expected
because DataList effectively resets upon being (re-)rendered.
The proper fix for this issue would involve rethinking the DataList
lifecycle with view-virtualization scenarios in mind, but this
would be a significant effort and the current DataList is on a
relatively short road to replacement, so for now we'll go with a
lighter-weight, Moonstone-specific solution.
In a nutshell, we remember both the current focus and the scroll …
=> ENYO-2744: moon/DataList: Restore state on render

src/DataList/DataList.js
In scenarios in which the DataList is re-rendered (e.g. when inside
a LightPanel that has moved offscreen), the list forgets the last
spotted row. Setting rememberFocusIndex to true causes it to remember.
=> Fixes ENYO-2744

src/Panels/Panels.js
According to UX guide, we add accessibilityLabel on PanelsHandle.
When panels is showing, it should be read 'close' + 'panel title'.
When panels isn't showing, it should be read 'open' + 'panel title'.
https://jira2.lgsvl.com/browse/PLAT-10833
=> PLAT-10833: Add Text to Speech Accessibility support to PanelsHandle

src/ExpandableInput/ExpandableInput.js
Issue
-------
VKB is showing up again when we click 'enter' button without mouse moving
Cause
--------
Recently added event like {{keyboardStateChange}} and {{webOSMouse}} will trigger {{spotlightBlur}} event. moon.ExpandableInput has a {{spotlightBlur}} event hander which toggle drawer.
Its purpose is closing drawer when user clicks outside of drawer.
But it toggles drawer from close to open when {{spotlightBlur}} event is triggered.
Fix
----
Add a condition to condition check.
=> ENYO-2751 Prevent to toggle drawer when spotlightBlur event triggered

src/Spinner/Spinner.less
Cause
--------
This issue for ltr case is fixed with Blake's fix, but rtl case, we need more.
Fix
----
I suggest margin-left:1 px and margin-right:1px for eliminating the blip
Then, we can handle ltr case with margin-right: 1px and rtl case with margin-left:1px
Enyo-DCO-1.1-Signed-off-by: Suhyung Lee suhyung2.lee@lge.com
=> the spinner ball is not perfectly circular in rtl case

src/Panels/Panels.js
Issue
When opening DynamicPanelsSample, undefined error occurs.
Cause
null checking is omitted
Fix
add null checking for active panel
https://jira2.lgsvl.com/browse/ENYO-2782
=> ENYO-2782: fix for PLAT-10833 makes undefined error

src/DataList/DataList.js
_indexToFocus was only updated after a control had been spotted and did
not respect initialFocusIndex. Alter the logic in didRender() to use
that value if _indexToFocus had not been set.
=> Fixes ENYO-2797

src/GridListImageItem/GridListImageItem.less
It was removed ages ago with reliance on a mixin, then later the mixin was changed to be more efficient to omit the color when it wasn't explicitly requested and this was dependent on that, and it slipped through review undetected.
=> ENYO-2728: Restored the caption color assignment to GridListImageItem

src/Scroller/Scroller.js
Previously checked against the kindName which is not always
predictable >= 2.6. Further, it assumed a kindName defined in
moonstone/ScrollStrategy which introduced some unnecessary coupling
such that a change in the kind used for paging controls would require a
change in moonstone/Scroller.
Instead, we'll use the ScrollStrategy's isPageControl() method, if it
exists, to check if the last spotted control should be checked for a
boundary. Also moved that check out of the job as it's inexpensive and
avoids a scenario in which the last control may have changed before the
job fires.
=> Fixes ENYO-2812

src/RadioItem/RadioItem.less
The default value, baseline, produced extra space below the baseline to
account for characters that would below. As a result, the new scroll to
boundary logic would animate a slight scroll when the last RadioItem in
a scroller was spotted. Since RadioItem isn't designed to be used
inline with text, we'll specify the vertical-align to middle so all
are aligned correctly without the space below the baseline.
=> Fixes ENYO-2814

src/Dialog/Dialog.js
specify a11y reading order for Dialog to match UX
=> Fixes ENYO-2764

src/Slider/Slider.js
The logic within spotlight to handle cancelling the hold is subverted
because Slider disables the jump button onSpolightKeyDown (before
spotlight registers the button as the last 5-way control) so
_onDisappear doesn't cancel the hold (again because it wasn't
registered as the last 5-way control).
A more thorough refactoring of Slider would be warranted but manually
cancelling the hold when not accelerating and when the spotlight has
changed jump buttons resolves the issue in the interim.
=> Fixes ENYO-2815

src/ScrollStrategy/ScrollStrategy.js
When scrolling with mousewheel before the scroll bars had been set up,
the showing of the scroll bars would cause a resize and invalidate
scrollBounds. This caused mousewheel to throw and exception. Reordering
the calls resolves this behavior.
=> Fixes ENYO-2833

src/ExpandableListItem/ExpandableListItem.less, src/LabeledTextItem/LabeledTextItem.js, src/LabeledTextItem/LabeledTextItem.less
Alter the CSS of LabeledTextItem without text to match Item sizing
Move logic into observer from binding transform and remove showing
logic to prevent overriding ExpandableListItemHeader's textShowing
Update ExpandableListItem to override .with-text for specificity
Issue: ENYO-2837
=> Fixes ENYO-2837

src/NewDataList/NewDataList.js
In moonstone/NewDataList, we guard 5-way move events to avoid
trying to focus list elements that don't yet have DOM nodes. This
case can occur during rapid 5-way scrolling.
Our guard logic didn't properly account for right-to-left mode, so
we fix that now.
At the same time, fixing a typo ('horizintal' -> 'horizontal')
that would have caused failures in other cases, and making some
minor tweaks to variable names and expressions for enhanced
readability.
=> ENYO-2839: moonstone/NewDataList: Fix 5-way guard code in RTL

src/Scrollable/Scrollable.js
We revert the previous fix for ENYO-2644, which cased the regression described in ENYO-2783, and make a minor change to support the new fix. Most of the work for the new fix is done in ENYO -- see the related PR: https://github.com/enyojs/enyo/pull/1331.
ENYO-DCO-1.1-Signed-Off-By: Gray Norton (gray.norton@lge.com)
=> ENYO-2783: Revert previous fix for ENYO-2644, implement new one

src/Tooltip/Tooltip.js
The default tooltip direction is towards the right which causes text to align left no matter what locale it is. This can result in unwanted left alignment for RTL languages.
Change the default direction of tooltip to face left-wards for RTL as a default.
=> ENYO-2832: Adjust tooltip direction towards left by default in RTL

src/ExpandableListItem/ExpandableListItem.js
=> Fixes ENYO-2847 propagate 5-way direction when respotting ExpandableListItem child

src/LightPanels/LightPanel.js
If Spotlight has currently been frozen (i.e. we have spotted an `Input`), the `unspot` call for a deactivating panel will exit early and not perform the desired operations (such as nulling out the currently spotted control). This results in the control's Spotlight disappear routine being run. Previously, this did not cause any side effects as the first child of the root (the default control to spot in these cases) was not spottable. But a recent change via https://github.com/enyojs/spotlight/pull/229 caused Spotlight to attempt to spot the disappearing control's closest spottable parent, as well, preventing the incoming panel from being spotted.
We call `unfreeze` if we have a currently spotted item in the panel that is being deactivated. Regardless of whether or not the first child of …
=> ENYO-2866: Unfreeze when deactivating panel with spotted control.

src/Tooltip/Tooltip.js
Tooltip is cut off in the panels when locale is rtl, because
* Tooltip doesn't calculate panel's breadchromb width.
* Tooltip miscalculate 'moonDefaultPadding' in adjustPosition function.
* So far, I couldn't find proper way to calculate panel's breadcumb. So apply 'floating:true' on tooltip although it is a big change.
* Take away 'moonDefaultPadding' from the original code for deciding 'anchorLeft'
Enyo-DCO-1.1-Signed-off-by: Sungbae Cho sb.cho@lge.com
=> adjust Tooltip's posistion when locale is rtl

src/DataList/DataList.js
=> Fixes PLAT-13387 add super call to beforeTeardown because we added a beforeTeardown method to enyo/DataList

src/SimplePicker/SimplePicker.js
If controls are added to the SimplePicker after it is created but
before it is rendered, the internal state is updated correctly. The
guard appears to be there to avoid unnecessary work which will be done
during create() so we'll use the internal state member, _created, to
guard instead of generated.
=> Fixes ENYO-2597

src/ContextualPopupDecorator/ContextualPopupDecorator.js
add spotlight container to ContextualPopupDecorator
Keeps the spotlight on the activator when the last spotted control is
within the popup before it hides.
=> Fixes ENYO-2230

css/moonstone-variables.less, src/ExpandableListItem/ExpandableListItem.less, src/Item/Item.less, src/LabeledTextItem/LabeledTextItem.js, src/LabeledTextItem/LabeledTextItem.less
* All items with only one line are now 60px tall.
* All 2 line items are 102px tall (42px taller, for the smaller second line).
* Items inside Items are 45px tall. (Equivalent to 1.7em, for tall-glyph support). _This seemed safer than using `em` in case font size changed._
=> ENYO-2838: Normalized the heights of Item, LabeledListItems, and Expandables

src/Panels/Panels.js
Do not read the PanelsHandle if the hidden handle is refocused in the screen without any focused item
The focused panelHandle is not blurred when screen has not any spottable item.
Set panelHandle to blur when panels is hidden and screen has not any spottable item.
https://jira2.lgsvl.com/browse/ENYO-2804
=> ENYO-2804: Set panelHandle to blur when panels is hidden

src/Popup/Popup.js
Issue:
The return statement is removed from getShowing while converting syntax for
2.6 toolchain.
Fix:
Add return back to getShowing
Enyo-DCO-1.1-Signied-off-by: Kunmyon Choi kunmyon.choi@lge.com
=> ENYO-2955:

src/LightPanels/LightPanel.js
Rule : Before reading focused child item, TV must have alert role for reading panel title.
Reading order must be guaranteed.
https://jira2.lgsvl.com/browse/ENYO-2784
=> Enyo 2784: When the LightPanels are switched, screen reader doesn't read the focused item

src/IntegerPicker/IntegerPicker.js, src/SimpleIntegerPicker/SimpleIntegerPicker.js
TV can read only simpleIntegerPicker's value and unit whenever
value or unit is changed, so accessibilityValueText is necessary for
reading other custom string.
https://jira2.lgsvl.com/browse/PLAT-14806
=> PLAT-14806: Add accessibilityValueText for reading custom string

css/moonstone-variables-dark.less
This will have *no* visible effect right now (the two values are the same color), but if one changes in the near future, this will be relevant. Also important for customization for the public release.
=> ENYO-3075: ContextualPopup should use the neutral BG color, not its own.

src/PagingControl/PagingControl.js
Due to some refactoring for accessibility, we separated out the logic for handling `onSpotlightKeyUp` and `onSpotlightBlur`. As a result, the call to `endHold` was only being made when handling `onSpotlightKeyUp`, and pressing a 5-way key to move off of the held `moonstone/PagingControl` control did not stop the scrolling.
We have added a call to `endHold` when handling `onSpotlightBlur`, and have moved/consolidated the clean-up logic into the `endHold` method.
=> ENYO-3036: End hold job when control is blurred.

src/CheckboxItem/CheckboxItem.less
When the locale was LTR but the CheckboxItem's text directionality is RTL, the checkbox item would
be right-aligned causing it to overlap with the content.
Use `right: auto` for left-handed checkboxes to override the default `right` value set for the checkbox.
=> Fixes ENYO-2907

src/DateTimePickerBase/DateTimePickerBase.js, src/ExpandableInput/ExpandableInput.js, src/ExpandableListItem/ExpandableListItem.js, src/ExpandablePicker/ExpandablePicker.js
We want to support the back key in `Expandable*` controls (basically, anything that subkinds `moonstone/ExpandableListItem`), such that pressing the back key closes the control if it is open and has Spotlight focus.
We have added this functionality primarily to `moonstone/ExpandableListItem`. Specifically, we have converted this control to be a Spotlight container to allow for easier handling of both the header + drawer as a whole, and we maintain an internal property to ensure we only add/remove history entries as appropriate. We have also added some logic to `moonstone/DateTimePickerBase` and `moonstone/ExpandableInput` to reset their respective values when the back key is pressed.
I considered adding an API called `resetOnBack` (or something to that effect) that would be defaulted to …
=> PLAT-15389: Add back key support to Expandables.

src/ContextualPopupButton/ContextualPopupButton.js, src/ToggleText/ToggleText.js
We should deprecate the entire `ContextualPopupButton` module, and not just the class.
The entire module has been marked as deprecated. As a bonus, we did the same thing for `ToggleText`.
=> PLAT-16231: Deprecate entire module

src/NewDataList/NewDataList.js, src/Scrollable/Scrollable.js
Issue
: NewDataList restore worng focus
Fix
: Before focus to first visible item, add condition that the item is visible or not in screen
Enyo-DCO-1.1-Signed-off-by:Changgi Lee changgi.lee@lge.com
=> ENYO-3074 Focus to wrong item in NewDataList

src/Slider/Slider.js
Class assignment was sprinkled throughout the kind making it more
difficult to reason when the classes would be applied (and introducing
a minor bug in which the bar would not be highlighted when dragging
started off the knob). Consolidating them into property observers
simplifies things.
Issue: PLAT-15388
=> refactor knob/bar class updates into property observers

src/Slider/Slider.js, src/Slider/Slider.less
Squashed version of https://github.com/enyojs/moonstone/pull/2687.
PLAT-15388: Remove spotlight color in progress bar
PLAT-15388: Show popup on focus
PLAT-15388: Cleanup and change name for hideKnobStatus
PLAT-15388: Change bar to highlight on press
PLAT-15388: Remove selected status on knob up
refactor knob/bar class updates into property observers
Class assignment was sprinkled throughout the kind making it more
difficult to reason when the classes would be applied (and …
=> PLAT-15388: Change Slider default focus behavior

src/Drawers/Drawers.js
When the drawer has been opened and has shifted some of its contents down, focusing on the shifted contents can cause some unexpected shifting, due to the contents being focused by accessibility and scrolled into view.
We have used the `accessibilityPreventScroll` property on `moonstone/Drawers` to prevent this unwanted shifting.
=> ENYO-3109: Prevent unwanted shifting of drawer contents.

src/Panels/Panels.js
The previous behavior (in standard Moonstone) was to disable the panel handle when using the activity pattern, if `useHandle: 'auto'` was specified. When making some changes to consolidate some logic (I believe related to the close button), this logic was changed so that the default in this scenario is reversed (panel handle is enabled).
I considered making a documentation change such that both the activity and always-viewing patterns behaved the same with respect to the panels handle and a value of `auto` for `useHandle`, but this would effectively defeat the purpose of having the `auto` value of the `useHandle` property and would effectively change the default behavior for the use of activity panels, even if the handles were not intended to be used. I am not quite sure why this has not …
=> ENYO-3149: Disable handle, by default, when using activity pattern.

src/ExpandableDataPicker/ExpandableDataPicker.js
If the client code relies on the data in the collection to drive the
initial selection, it will not do so on create because the repeater has
not rendered yet so the onActivate event doesn't fire. So, if the
collection for an ExpandableDataPicker changes and the list hasn't
rendered yet, force a refresh to trigger the onActivate event, update
the selected item, and display the correct text in currentValueText.
=> Fixes ENYO-3101

src/Panels/Panels.js
We had made a tweak in https://github.com/enyojs/moonstone-extra/pull/167 to prevent running the `indexChanged` logic when there are no panels. Unfortunately, there are certain scenarios where `createComponent[s]` is utilized to create a single panel, and was relying on the fact that `indexChanged` was run unbounded, which adjusted the viewport to be full-width as the default index is 0.
We moved the call to adjust the panel out of the guard, in `indexChanged`.
=> ENYO-3161: Always adjust panel when changing indices.

src/ContextualPopup/ContextualPopup.js
The components outside the contextual popup were not spottable even after the spotlightModal property set to false for the contextual popup. The spotlightModal property doesn't use for show/hide the scrim which caused this issue.
It was the modal property used for show/hide the scrim, so that the modal and spotlightModal are binded together and the this.showHideScrim() function called on modelChanged will solve the issue.
Enyo-DCO-1.1-Signed-off-by: Kunmyon Choi kunmyon.choi@lge.com
=> ENYO-1224: ContextualPopup: Nothing is Spottable outside of Spotlight Modal Off

src/VideoPlayer/VideoPlayer.js
We had been utilizing the non-standard `Event.srcElement` property (https://developer.mozilla.org/en-US/docs/Web/API/Event/srcElement), which is not supported at all in Firefox, and was throwing fatal errors.
We have made an update to utilize the standard `Event.target` property, instead.
=> ENYO-3184: Utilize standard Event property target, instead of srcElement.

src/Header/Header.less, src/Input/Input.less
=> ENYO-3183: Corrected opacity level for input Headers' placeholders

src/Item/Item.less
This is a low-specificity rule that is/will be easy to override, if some case finds a reason to need to.
=> ENYO-3186: All children of spotted items get a reasonable color.

css/moonstone-spacing.less, src/Header/Header.js, src/ListActions/ListActions.js, src/ListActions/ListActions.less
We're going to change `ListActions` from `Drawer` to a `ContextualPopup` for 2017 TV.
Following are some of the notable changes from existing ListActions
- The base kind for `ListActions` is `ContextualPopupDecorator`.
- `open`, `autoCollapse` and `proportionalWidth` properties are removed.
- No longer stacks. (assumes there would be maximum of 3 columns horizontally)
- `Header` no longer handles events from `ListActions`.
- `listActions` block no longer use `FittableRowLayout`.
- Fix the height of scrollable area to `height: 300px`.
- Unlike `ContextualPopup`, the new ListActionPopup sets `spotlightModal: true` and `showClosebutton: true` by default.
- Popup is anchored to the right and points arrows aligned to the center of `IconButtons`. If the width is not wide enough to touch the …
=> ENYO-2959: Change ListActions with new design

src/ListActions/ListActions.js
Rebased #2753 on 2.6.0-dev
ListActionPopup extends contextualPopup, so alert role is set, then
TV will read all contents when ListAction popup is opened. To prevent it,
we add accessibilityReadAll:false to ListActionPopup
=> PLAT-17663: Prevent reading ListAction's content

src/ExpandableText/ExpandableText.js
The `-webkit-line-clamp` property is only supported in WebKit, and there is no standards-based version of this property to utilize for other browsers.
We have added a note to the inline documentation to identify this limitation.
=> ENYO-3199: Adding note about ExpandableText WebKit limitation.

src/Marquee/Marquee.js
Because we are lazily creating the `marqueeText` control, we initially use the bounds of the control we wish to add marquee support to. When this control has a border, the border is added to the width and we compute a marquee distance that is short by the sum of the left and right border width. This value is cached and used for the `marqueeText` control when it is created, causing it to not marquee the correct distance.
It didn't seem like we needed to specifically measure the bounds of the control that was mixing in marquee support, and that we should always base our measurements on the `marqueeText` control for maximum accuracy. As a result, we guard against distance calculation until the {{marqueeText}} control has been created. This effectively relies on the `text-overflow:ellipsis` …
=> ENYO-2846: Always calculate distance using marqueeText control.

css/moonstone-variables-dark.less, css/moonstone-variables-light.less
This was originally the result of several complex merges and conflicts, as well as new line numbers. Related hashes: 1d3f8ae610996beb1886c1ef2e6f4a58a393320b, 3444b6af9c9b9604ce5c3737b27bc759888bb3cb, 7647ddf982e9318fe51d513754cd1c7a0b059cde
Original version/value: 0f91d4b97d05cbfcc53d2d39d21a84fb8584118c
=> ENYO-3221: Removed conflicting lighter definition of @moon-gray

src/IntegerPicker/IntegerPicker.js, src/NewPagingControl/NewPagingControl.js, src/PagingControl/PagingControl.js
Due to the changes in https://github.com/enyojs/enyo/pull/1414, the API being used has been deprecated.
Updated to use `cancelAnimationFrame`.
=> ENYO-3222: Use updated cancelAnimationFrame API.

src/ContextualPopup/ContextualPopup.js
Issue
---
`TooltipDecorator` hides tooltip when it receives `tap` event. When close button is tapped in `ContextualPopup` that is wrapped in a `TooltipDecorator`, the `tap` event to close the `ContextualPopup` will bubble up the chain and gets handled by the `TooltipDecorator`.
Fix
---
Consume tap event on `ContextualPopup` and prevent bubbling further.
=> ENYO-3233: Prevent event bubbling when close button is tapped

src/Panels/Panels.js
When `setIndex` is used on `moonstone/Panels` at create time, the breadcrumbs (if visible) and close button are not spottable.
The bounds are not available at create time, so we move the call to update the breadcrumbs into `rendered`. Additionally, we only disable Spotlight on the close button if there will be an animated transition, as `finishTransition` will not run otherwise.
=> ENYO-3163: Update breadcrumbs when bounds are available.

src/Panels/Panels.js
According to TV UX guideline, TV should read 'go to previous' when
BreadCrumb is spotlight focused, so set to this string using accessibilityLabel
https://jira2.lgsvl.com/browse/PLAT-17664
=> PLAT-17664: Add accessibilityLabel to read breadcrumb label

css/moonstone-spacing.less, src/Header/Header.js, src/ListActions/ListActions.js, src/ListActions/ListActions.less
ENYO-2959: Remove ListActionDrawer related handlers from Header
ENYO-2959: Remove extra margins added to decorators in moon-hspacing
Prevent tooltips to appear when popup is shown
Apply FittableRowsLayout to listActions block
ENYO-2959: Remove FittableLayout and fix defaults for ListActionPopup
ENYO-2959: Fix margins for list action icon buttons with tooltip decorator and RTL cases
Enyo-DCO-1.1-Signed-off-by: …
=> ENYO-2959: Change ListActions to new design using ContextualPopups

src/ProgressBar/ProgressBar.js
When changing from a falsy value to another falsy value, the deprecated `setContent` was using a standard equality check that prevented the content from updated (i.e. from the empty string `''` to `0`).
We utilize the generic setter, which will update the content in these cases. Also, in `popupContentChanged`, we are guarding against setting a `null` or `undefined` value for the popup content. We update this guard to prevent setting of empty string content, and have also added this guard to `updatePopupLabel` for consistency.
=> ENYO-3244: Use generic setters and enhance guards.

src/Slider/Slider.js
slider's hint message is set whenever user selects it, but message is not
initialized when slider is blured, so TV read hint message instead of
value when this slider is spotlight focused again.
https://jira2.lgsvl.com/browse/ENYO-3236
=> ENYO-3236: set accessibilityHint to null when slider is blur

src/Panels/Panels.js
If panels's animate is false and arranger is cardArranger, close button
is always spottable, then close button is spotlight focused when panel is
changed, so TV reads 'exit app' + panle title + focused item.
https://jira2.lgsvl.com/browse/ENYO-3239
=> ENYO-3239: set close button's spotlight to false when panel is changed

src/ProgressBar/ProgressBar.js, src/Slider/Slider.js
When `lockBar` is set to `false`, dragging the knob does not result in updated popup values. Additionally, there were some latent bugs, such as setting the `showPercentage` property resulting in non-sensical popup value, and similarly when setting the `popupSide` property. A lot of this stems from a mismatch between `ProgressBar` and `Slider`, as the former relies on the value of `progress`, while the latter relies on the `value` property. 
Instead of using `this.progress` when updating the popup, we now use the passed-in value. I didn't see any issues with this, as the value passed from `updateValues` is already clamped, and the calls to `updatePopup` in other instances are either a result of user interaction, which would pass valid values, or programmatic calls that are just passing …
=> ENYO-3243: Allow for popup value updating during knob dragging, fixing some latent bugs.

css/moonstone-variables-dark.less, css/moonstone-variables-light.less, css/moonstone-variables.less, src/Input/Input.less, src/InputDecorator/InputDecorator.js, src/InputDecorator/InputDecorator.less, src/TextArea/TextArea.less
Adding an input validation messaging feature, which gives apps control over whether or not the "invalid" message appears via a tooltip. It seemed to make sense to effectively have `InputDecorator` own this functionality, as the "invalid" message tooltip would be decorating the input. The only APIs added to `Input` control the `min` and `max` properties, as those are input-specific, while the APIs added to `InputDecorator` control validity state and messaging. Additionally, because it would be heavy-handed to pre-create the tooltip for all `InputDecorator`s, we lazily create the tooltip. Lastly, had to make a tweak to the positioning of `InputDecorator` so that the tooltip can be properly positioned.
=> PLAT-16501: Adding input validation.

css/moonstone-variables.less, src/VideoTransportSlider/VideoTransportSlider.js, src/VideoTransportSlider/VideoTransportSlider.less
There are myriad issues with the slider knob, including thrown exceptions if pressing and holding or pressing and dragging the knob when the controls disappear, and unnecessary handling of an `Infinity` time value. Additionally, the pressed state is not always cleaned-up.
To fix the pressed state issues, we have effectively cherry-picked the changes from https://github.com/enyojs/moonstone-extra/pull/191. To fix some of the other issues, such as the progress being set to the end, after dragging and holding with the controls hiding, we now "complete" any in-progress drags when the controls are hidden. This prevents any undesired changing of the progress while the controls are hidden, and resolves the edge case with the `Infinity` time value. We have also fixed the setting of an `Infinity` …
=> ENYO-3093: Fix-up slider knob issues

src/Panels/Panels.js
Reverts some async logic from 8f3f98a3, 688b9e02, and fb1d836e which
is no longer necessary. The original dual-spotlight issues no longer
appear (for reasons unknown).
=> Fixes ENYO-3238 send the onPanelsHidden event synchronously

src/ListActions/ListActions.js
Issue
---
By overriding resize function, it prevented from ScrollStrategy to set correct bounds or properly update page control scroll thumbs. 
The original fix was related to `DataList` re-rendering on resize, and it's addressed in https://github.com/enyojs/enyo/pull/1421.
Fix
---
The Let onresize event to waterfall.
=> ENYO-3230: Let onresize event to waterfall

src/ListActions/ListActions.js
ENYO-3230: Let onresize event to waterfall
Update document for the edge case with DataList and autoCollapse
ENYO-3230: Update document to reflect known issue with DataList and autoCollapse
=> Fixes ENYO-3230

src/Tooltip/Tooltip.js
=> ENYO-3271: Account borders when calculating left position for right tooltips

src/Panels/Panels.js
If the close button were spotted when the panels are hidden, the
disappear logic would fire causing spotlight to bounce unnecessarily
causing issues for a11y. Shifting the showing update to the end of
Panels.showingChanged prevents this bouncing without any visual change.
=> Fixes ENYO-3281

src/Panels/Panels.js
This is a regression due to a recent change in https://github.com/enyojs/moonstone/pull/2776 to only disable spottability of the close button when necessary (and not fully fixed by https://github.com/enyojs/moonstone/pull/2787), the highly-sequential ordering of operations was modified, as the call to `shouldAnimate` relies on both the assignment of `this._willMove = null` and also `this.fromIndex = this.index` and `this.toIndex = index` to properly determine the return value. As a result, `shouldAnimate` was incorrectly returning `false` for the first transition, which caused the `adjustFirstPanelBeforeTransition` method to incorrectly remove the `first` class before the transition (because `startTransition` was never run, which sets the value of `this.transitioning`). This led to an …
=> ENYO-3301: Fix order of operations for panel transition.

src/Panels/Panels.js
For panel arrangers that hide (or otherwise cause a disappearance of) panels that are transitioned away from, Spotlight's disappearance logic can cause the destination panel to be spotted, which is followed by the logic in `finishTransition` again spotting the destination panel. This can cause unwanted and repeated accessibility readouts.
We detect if the destination panel (or one of its children) has already been spotted, and only spot the destination panel if this is not the case.
=> ENYO-3300: Prevent re-spotting of the same panel.

src/Slider/Slider.js
Enable jump buttons before disabling them.
Avoids spotlight moving focus off the slider when both buttons are
temporarily disabled during switching.
=> Fixes ENYO-3332

src/ExpandableInput/ExpandableInput.js, src/InputDecorator/InputDecorator.js
Change 'edit box' string to 'Input field' base on UX request
=> ENYO-3317: Change 'edit box' string in audio guidance

src/ContextualPopup/ContextualPopup.js, src/Popup/Popup.js, src/Tooltip/Tooltip.js
Issue
: Read sequence is not match to UX Guide
Fix
: Change read sequence at Popup, Contexture Popup
=> ENYO-3260 : Change audio guidance read sequence

src/SimplePicker/SimplePicker.js
According to accessibility UX changes, change simplePicker's hint message.
https://jira2.lgsvl.com/browse/ENYO-3318
Change-Id: Ifc28fe881c0ef257702ce80afe3c61db769ea910
=> ENYO-3318: Change audio guidance string in SimplePicker

src/Slider/Slider.js
Avoids spotlight moving focus off the slider when both buttons are
temporarily disabled during switching.
Issue: ENYO-3332
=> enable jump buttons before disabling any

src/LightPanels/LightPanel.js
Issue:
window.focus is bypass during light panel transition.
Fix:
unmute and udpate pointer status in postTransition handler
=> ENYO-3363 : Initial focus is not shown in light panel

src/DayPicker/DayPicker.js, src/ExpandablePicker/ExpandablePicker.js
Current value of DayPicker is showing abbreviation even when each item
is showing full string. This is to show as many days as possible in
small control space. When current value is 'Mon, Tue, Thu, Sat', it
reads 'Day Picker Mon, Tuesday, Thursday, Sat'.
We bind accessibilityText to accessibilityLabel of header. Update
accessibilityText by concatenate content of each items whenever
currentValue changes. Also, it concatenate accessibilityLabel for
item when specified. This also fix the problem of read current
value of ExpandablePicker when multipleSelection is true. (ENYO-3355)
=> ENYO-3348: Read full string for current value on DayPicker

src/ContextualPopup/ContextualPopup.less
IconButton is used as ContextualButton. It's width is smaller than Button.
Plus, content or control in ContextualPopup is short in this problem case.
It is reproduced in the right side of the screen.
CSS Value 'right' is changed to fix it. 
It is reproduced because of '.moon-contextual-popup.above.left:after'. (or below)
In opposite direction (right), it is not reproduced.
Because value for left direction is different from value for right direcion.
ENYO-3347 ContextualPopup: knob position is wrong when IconButton is used as ContextualButton
=> ENYO-3347 ContextualPopup: knob position is wrong when IconButton is used as ContextualButton

src/Drawers/Drawers.js, src/ExpandableListItem/ExpandableListItem.js, src/GridListImageItem/GridListImageItem.js, src/Icon/Icon.js, src/ImageItem/ImageItem.js, src/LabeledTextItem/LabeledTextItem.js, src/LightPanels/LightPanel.js, src/Panel/Panel.js
According to TV UX requirements, TV should support to reading a
hint message before reading control's content or aria-label, so
accessibilityPreHint API is added in enyo AccessibilitySupport,
we also applied it to Moonstone components.
https://jira2.lgsvl.com/browse/ENYO-3326
Change-Id: I71cc0d9fe117009d5cd31c8c96aff2cd9b1b6e59
=> ENYO-3326: Support accessibilityPreHint

src/Button/Button.js, src/Dialog/Dialog.js, src/Tooltip/Tooltip.js
In the moonstone button case, it has not aria-label. So, aria-label is set to upper-cased string.
If uppercased content is read from TTS engine, it's pronounciation can be wrong.
For example, you can see this sentence ("Reset a device").
In this case, 'a' is article grammartically, not captial 'A'.
It is to fix issue about above accessibility.
I modified button, tooltip and dialog for setting 'aria-label' from origin content.
ENYO-3366 Accessibility: aria-label is set to uppercased string
=> ENYO-3366 Accessibility: aria-label is set to uppercased string

src/Button/Button.js
ENYO-3366 (regression) Accessibility: aria-label is set to uppercased string
=> ENYO-3366 (regression) Accessibility: aria-label is set to uppercased string

src/Slider/Slider.js
Although there is an incremental option popup still shows unexpecting point number.
To resolve this, I override calcPopupLabel() to make corresponding values.
=> ENYO-3331: Apply incremental option to popup animation

src/Popup/Popup.js
We didn't expect client, closeButton as returns of getClientControls().
To get corresponding return, we added isChrome option when creating tools.
=> ENYO-3344: add isChrome options when creating tools

css/moonstone-variables.less
moon-font-family-small wasn't defined in moonstone but moonstone-extra.
It caused less compile fail. So I changed that variable to real value temporally.
=> ENYO-3309: Change undefined less variable to real value

src/TimePicker/TimePicker.js
Due to earliness of ariaObserver, date and range weren't set as our expectation.
To resolve this scenario, we put ariaValue() at the end of TimePicker creation time.
=> ENYO-3373: Call ariaValue() explictly at the end of TimePicker creation

src/Scroller/Scroller.js
Issue:
Scroller can handling page up/down key. When nearest neighbor control
exist from the last focused control, it spot on it. When the nearest
neighbor control is same as last focus control, it send paging event to
scroller. Problem happens when nearest neighbor control is null. It is
trying to spot on null which doesn't do any movement.
Fix:
Adding check for null case and send paging event to scroller.
=> ENYO-3377: Scroller doesn't scroll on page up when focused item is not visible on viewport

src/Input/Input.js
Issue:
When user press left or right key in moon.Input, it compares the cursor
position to 0 or length of text and move spotlight focus to other
control to that direction. Problem happens on rtl character. It compares
start position to 0 but it should compare to length.
Fix:
When rtl character is written in moon.Input, flip the start and end
position of compare. So it can safely move focus to the right direction.
=> ENYO-3390: Flip start/end compare position on rtl case in moon.input

src/Marquee/Marquee.js
Issue
:Marquee status change to ellipse but animation is not working
Fix
:Call marquee reset func in reflow handler
=> ENYO-3391 : Marquee is not working when reflow is happen

css/moonstone-variables.less, src/Button/Button.less, src/IconButton/IconButton.less, src/Popup/Popup.less
Added translucent&transparent visual states to Button, to match IconButton
Assigned darker color value to transparent neutral buttons (so it's not white on off-white)
=> ENYO-3330: Darkened Popup's buttons

src/ExpandableListItem/ExpandableListItem.js, src/ScrollStrategy/ScrollStrategy.js
Issue:
We added Scroll to boundary feature on ScrollStrategy which is checking
5way limit with its first spottable parent. When spotlight container
control is used in scroller with spottable child inside, it is detect
there is no nearest neighbor from the child and try to jump scroll.
This behavior is okay with other case but it is not when child items are
small number like ExpandableListItem Header case. It is try to jump
scroll for every 5way key.
Fix:
Set nearest neighbor root as focusable parent that is having more than
1 children.
=> ENYO-3379: Set ExpandableListItem spotlight property as false

src/Notification/Notification.js
Previously, Dialog supported allowHtml as true by default.
It was caused by not binding Dialog's allowHtml to BodyText.
In case of Notification we binded its allowHtml to BodyText and it caused
settings BodyText's prop to false by unexpectation.
=> ENYO-3412: Assign allowHtml as true by default

src/ExpandableInput/ExpandableInput.js
Issue: Expandable Input doesn't expand when touched.
Cause: touch is generated with a mousedown event. tap event makes the
input to expand and the following mousedown will make the expandable
input to collapse
Fix: When the event is triggered from touch, the default event
(mousedown) is prevented.
Enyo-DCO-1.1-Signed-off-by: Rajyavardhan Reddy P
<rajyavardhan.p@lge.com>
=> PLAT-21870-touch issue with ExpandableInput

src/Notification/Notification.js, src/Popup/Popup.js
spotlightRememberFocus is false
Remove spotlightRememberFocus on Popup and Notification.
Calling requestClearLastFocus event so container can forget last focus
on hide.
=> ENYO-3425: Nearest neighbor compare position with first child when

css/moonstone-variables-dark.less, css/moonstone-variables-light.less, src/FormCheckbox/FormCheckbox.less
Issue
:netural css property effect to color. So mark color similar to background.
Fix
: Change mark color
=> ENYO-3433 : FormCheckbox's check mark is not shown.

src/Notification/Notification.less
Many buttons can cause overflow on Notification control.
We guard this by setting overflow as hidden to client per UX requirement.
=> ENYO-3389: Set overflow as hidden to client control

src/ExpandableListItem/ExpandableListItem.js
spotlightPreserveAcceleration property as true.
When spotlight container control have only one spottable item,
just like ExpandableListItem family, it cancel 5way key acceleration.
We add a property which can be given on container control that
is skipping acceleration cancel logic.
=> ENYO-3430: Preserve acceleration when container control have

src/Notification/Notification.js
Issue
:When Notification Popup is opened,
Button focus is called straightly, but Alert is called after 100ms.
So, Alert message is cut off button's tts audio guidance.
Fix
:Change Alert called timing to onSpotlightContainerEnter event handler
=> ENYO-3427 : Button label did not read when Notification Popup is shown.

src/ListActions/ListActions.js
Issue
:UX request read category name before item label
Fix
:When containerEnter event fired, read category name using by accessibilityAlert property.
=> ENYO-3378 : Read category bofore focused item label in ListAction

src/Notification/Notification.js, src/Popup/Popup.js
Scrim is not hidden when notification is destroyed in showing status.
When notification is destroyed, showHideScrim is called to hide scrim.
ENYO-3431 Scrim isn't hidden when notification is destroyed in showing
=> ENYO-3431 Scrim isn't hidden when notification is destroyed in showing

src/NewDataList/NewDataList.js
Issue: In touch devices, Moonstone NewDataList doesn't scroll with touch.
Cause: By default, touch was disabled in Moonstone NewDataList by setting the code touch: false
Fix: Removed the code touch: false, by default the touch is enable in Enyo NewDataList
Enyo-DCO-1.1-Signed-off-by: Anish T D(anish.td@lge.com)
=> PLAT-23893: Fix touch issue with NewDataList

src/Scroller/Scroller.js
PLAT-21871: Fix touch issue with ListActions
Issue: On portrait mode non webOS devices, List Action 5way navigation focuses the items on next column .
Cause: For non webOS touch devices enyo scroller will be loaded instead of moon scroller.
Enyo scroller is not a container, it is taking all other controls as potential neighbors. So by nearest neighbor algorithm, its jumps to items outside the current column.
Fix: Removed conditional check for loading the enyo scroller.By default moon scrollerwill be loaded for all.
PLAT-21869:  Fix touch issue with DataGridList
Issue: On portrait mode non webOS devices, DataGridList does not render .
Cause: For non webOS touch devices enyo scroller will be loaded instead of moon scroller.
DataGridList uses ScrollStrategy.vScrollColumnSize. For Enyo …
=> PLAT-21871:Fix touch issue with ListActions

src/Notification/Notification.js
Issue:
ShowingTransitionSupport is calling showingChanged from create. The
showingChanged is set initial css state and call timing methods like
hiding, hidden, showing, shown. Problem happens when create Notification
dynamically because hidingMethod is called on create and try to re-spot
on activator but activator is null (cached on showingMethod). And if
user destroy popup without hide, then hidingMethod is not even called.
Fix:
Call respotActivator only if initialized (rendered) on beforeHide.
=> ENYO-3444: respotActivator only if popup is rendered

css/moonstone-text.less, src/Notification/Notification.less
Issue
: When japanese language is selected, non-latin(LG Display) has to applied in Notification Popup's body text.
Fix
: Add optional code for  apply non-latin font.
=> ENYO-3438 : Apply non-latin font in Notification Popup

src/Input/Input.less
With newer web engines (i.e. Chromium 44+), the arrows (spinners) are displayed for inputs with `type="number"`.
We add some styling to hide the arrows specifically for these types of inputs.
=> Hides number input arrows

src/DataList/DataList.js
previous on LightPanels
Issue:
We remember last scroll position and focused item index on DataList when
teardown, then restore it on render if cached. The id of items are
different from previous render, so we refocus last focused item by
index.
We paused spotlight when LightPanels is transitioning to block any
unwanted focus change and resume it after render panel client.
But, this makes restoreState fails give focus on last focused item.
Fix:
We reset last focused child of panel when focusOnItem try to focus while
paused. So, that panel can safely remember last focused child and give
focus when it got focus after resume by checkSpottability.
=> ENYO-3457: Last focused item of data list is different when move back to

src/Notification/Notification.less
There was a bug on chromium side that set blur to font forcefully in
case of div's position is odd number.
To avoid this, we set blur(0) to -webkit-filter prop.
=> ENYO-3456: Set filter as blur(0) to avoid chromium bug

src/Tooltip/Tooltip.less
Issue:
Tooltip arrow is drawn as a svg element. It is absolutly positioned.
But, when tooltip is set direction rtl, sgv element moves its position
to opposit end. But, some right arrow case is having right: 0 and not
affected by direction change.
Fix:
We apply left: 0 for left arrow case also, so that it will not affected
by direction change.
=> ENYO-3449: Fix tooltip arrow position for rtl text case

css/moonstone-text.less, src/Notification/Notification.less
It's better to have word-break option to display context in various locales.
At this moment, we only applied it to BodyText in Notification.
For the expandability of word-break style, we separate it as an individual
css prop to use it in other controls.
=> ENYO-3447: Define .moon-word-break and use it in Notification

src/DayPicker/DayPicker.js, src/ExpandablePicker/ExpandablePicker.js
This is requirement from 'Gold Iran'.
They want to support special delimiter to moon.DayPicker.
Add method for getting delimiter(,) depands on Locales.
ENYO-3441 DayPicker: Support special separator for fa-IR locale
=> [ENYO-3441] DayPicker: Support special separator for fa-IR locale

src/Notification/Notification.less
There was a missing code that adding overrides for .enyo-locale-right-to-left
case. If we don't have that overriding prop, gap between buttons is 0.
We don't need to set margin-left as 0 in case of first-child since it's
already 0.
=> ENYO-3446: Set margin-right as 9px if locale is right to left

src/Notification/Notification.js
routine sets explicit height
Notification popup have a enyo-fill class on client area. But, it
doesn't actually affect layout.
When applied post size adjust feature to fix floating point position
problem, popup get specific width or height. And this makes enyo-fill
calculate its height as 100% popup height in relative position. As a
result, client area overflow popup area.
To fix this problem, we can simply remove enyo-fill from client.
=> ENYO-3486: Notification popup client overflow when position adjust

src/LightPanels/LightPanel.js
Issue:
LightPanel pause spotlight on preTransition and resume spotlight on
postTransition. And give default focus on active panel in async call.
Spotlight recover focus when pressing 5way key while current focus is
not spottable or when no focus under pointer in pointer mode.
This can lead unexpected focus jump to first control in screen if press
repeated 5way key while panel transitioning.
Fix:
We add an API that blocking _spotNearestToPointer. And, block this
behavior between resume and default spot.
=> ENYO-3467: Block _spotNearestToPointer while LightPanel is in transition

src/IconButton/IconButton.less
Issue:
Neutral text color of icon button is white on active. And this
is not recognizable on white background.
Fix:
Adjust color of transparent icon button text from white to dark gray.
Don't need to modify translucent or opaque because it have dark
background.
=> ENYO-3507: Adjust transparent icon button neutral text color

src/Dialog/Dialog.js, src/Dialog/Dialog.less
Issue:
GUI use dialog with no title and use small button for this case.
When there is no title, button have too much top margin and title area
have too much space on bottom.
Fix:
We conditionally change margin and min-height for no title case.
enyo-DCO-1.1-Signed-off-by: Kunmyon Choi (kunmyon.choi@lge.com)
=> ENYO-3455: Adjust dialog title and button area for no title case

src/DataList/DataList.js
Issue:
When data list update its list while item focused, data list remember
last focused item index on remove and restore it on add. When restore
focus, item content can be the same or different because it find item
based on index not content. When item restore focus on the item that
have the same content, TTS will read content. Problem happens when
update list frequently because it will read everytime it update.
Fix:
We add a property like 'primaryKey' just like collection, and skip read
when the key is the same.
=> ENYO-3490: Skip read when restore focus on same data list item

src/Marquee/Marquee.js
Issue:
startMarquee and stopMarquee with marqueeDelay 0 will cause marquee text
dissapear. This happens because _marquee_addAnimationStyles have 16ms
delay for set translateX position. If _marquee_removeAnimationStyles is
called between the 16ms gap, _marquee_addAnimationStyles can set value
for translateX after remove animate-marquee and set duration as 0.
This will make marquee stop but also translateX for some amount of
distance (hidden).
Fix:
Clear setTimeout timer before apply style.
=> ENYO-3546: Marquee doesn't show text after stop

css/moonstone-variables.less, src/ProgressBar/ProgressBar.less
There was a missing spec for Progress control when it displayed under
neutral class.
Dev/GUI team discussed about it and finalize spec as followings..
@moon-neutral-progress-bar-bg-color: #bbbbbb;
@moon-neutral-progress-bg-bar-bg-color: #909090;
@moon-neutral-progress-bar-bar-bg-color: @moon-dark-gray;
=> ENYO-3435: Apply new style for Progress control under neutral class

src/DataList/DataList.js
DataList._spotlightSelect() causes undefined reference on
VerticalDelegate.height().
I added guard code in DataList._spotlightSelect()
=> ENYO-3527: Guard up spotlight if DataList didn't rendered yet

index.js, src/options.js
Add brandTheme to moon.config (moonstone option).
Apply 'enyo-brand-theme-xxx' css on body when brandTheme is set on
build time.
=> ENYO-3616: Support brandTheme option for build time theme change

src/Marquee/Marquee.js
Issue:
Marquee is not remember puppet master when text fits content or it was
hidden when requested marquee.
Fix:
Remember puppetMaster regardless of adding Marquee item to wait list
or not.
=> ENYO-3572: Marquee doesn't flow on first set content

src/Notification/Notification.less
ja zh locale
Notification doing break line in word level. New requirement is break
line in work level for Japaniese Chinese locale.
=> ENYO-3657: Notification popup message should break line in character for
